<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $_layoutParams['ruta_img']; ?>favicon.ico">

    <title><?php echo $this->titulo;?></title>
    <link href="<?php echo $_layoutParams['ruta_bootstrap']; ?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $_layoutParams['ruta_css']; ?>signin.css" rel="stylesheet">

  </head>

  <body>