<div class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange">Equipos y Elementos Pendientes Por Entregar</h4></div>
                <div class="panel-body">
                    <div class="row">

                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-12  ">
                            <div class="table-responsive">
                                <table id="datatable" class="table table-condensed table-striped table-bordered table-hover">
                                    <thead>
                                        <tr class="warning">
                                            <th>Id</th>
                                            <th>Numero Inventario</th>
                                            <th>Tipo de Equipo</th>
                                            <th>Nombre de Persona</th>
                                            <th>Fecha del Prestamo</th>
                                            <th>Fecha Limite</th>

                                        </tr>        
                                    </thead>
                                    <tbody>
                                        <tr>
                                    <td ></td>
                                    <td ></td>
                                    <td></td>
                                    <td ></td>
                                    <td></td>
                                    <td ></td> 
                                   
                                        </tr>
                                       

                                    </tbody>


                                </table>
                            </div>
                        </div>
                    </div>
                </div></div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>