<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-12">
            <div class="panel panel-warning sombra">
               <div class="panel-heading"><h4 class="label-orange">Registrar  Equipos y Elementos</h4></div>
                <div class="panel-body">
                    <form id="form1" name="form1" class="form-horizontal" method="post" action="<?php echo BASE_URL . 'pee-cefa/reportes/saveelemento'; ?>">
                        <input type="hidden"name="txtId" id="txtId" value="<?php// echo $this->untrimestre[0]['tresId'] ?>" />
                        <fieldset>
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Número Inventario <sup class="text-danger">*</sup></label>
                                <div class="col-lg-6">
                                    <div class="col-md-10"><input type="text" class="form-control" name="txtNombreTipo" id="txtNombreTipo" value="" /></div>
                                </div>
                            </div>
                             <div class="form-group">
                                <label class="col-lg-4 control-label">Tipo De Elemento u Equipo<sup class="text-danger">*</sup></label>
                                <div class="col-lg-6">
                                    <div class="col-md-10"> <input type="text" class="form-control" name="txtNombreTipo1" id="txtNombreTipo" value="" /></div>
                                </div>
                            </div>
                             <div class="form-group">
                                <label class="col-lg-4 control-label">Marca<sup class="text-danger">*</sup></label>
                                <div class="col-lg-6">
                                    <div class="col-md-10"><input type="text" class="form-control" name="txtNombreTipo2" id="txtNombreTipo" value="" /></div>
                                </div>
                            </div>
                              <div class="form-group">
                                <label class="col-lg-4 control-label">Carecteristicas<sup class="text-danger">*</sup></label>
                                <div class="col-md-6">
                                    <div class="col-md-10"><input type="text" class="form-control" name="txtNombreTipo3" id="txtNombreTipo" value="" /></div>
                                </div>
                            </div>
                             

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Fecha del Registro <sup class="text-danger">*</sup></label>
                                <div class="col-lg-4">
                                    <div class="col-md-10"><input type="date" class="form-control" name="txtFecha" id="txtFecha"  value="<?php //echo $this->untrimestre[0]['tresFechaInicio'] ?>" /></div>
                                </div>
                            </div>

                           
                              <div class="form-group">
                                <label class="col-lg-4 control-label">Estado <sup class="text-danger">*</sup></label>
                                <div class="col-lg-6">
                                    <div class="col-md-10"><input type="text" class="form-control" name="txtNombreTipo4" id="txtNombreTipo" value="" /></div>
                                </div>
                            
                              </div>

                        </fieldset>
                        <div class="form-group">
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary" id="btnGuardar">Guardar</button>
                                <a class="btn btn-danger" href="<?php echo BASE_URL . 'pee-cefa/inicio /inicio'; ?>" >Cancelar</a>
                                <button type="button" class="btn btn-info" id="resetBtn">Limpiar</button>
                            </div>
                        </div>
                    </form>     
                </div>   
            </div>

        </div>
        <div class="col-md-2"></div>
    </div>
</div>