


<div class="form-group">
    <label class="col-md-6 control-label">Marca<sup class="text-danger">*</sup></label>
    <div class="col-md-6">
        <div class="col-md-12"><label class="text-left" name="txtMarca" id="txtMarca"><?php echo $this->info[0]['Marca'] ?></label></div>
    </div>
</div>
<div class="form-group">
    <label class="col-md-6 control-label">Tipo De Equipo u Elemento<sup class="text-danger">*</sup></label>
    <div class="col-md-6">
        <div class="col-md-12"><label class="text-left" name="txtNombreTipo" id="txtNombreTipo"><?php echo $this->info[0]['Tipo_equipo'] ?></label></div>
    </div>