<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-12">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange">Realizar Sanción</h4></div>
                <div class="panel-body">
                    <form id="form1" name="form1" class="form-horizontal" method="post" action="<?php echo BASE_URL . 'sigac/parametros/savetrimestre'; ?>">
                        <input type="hidden"name="txtId" id="txtId" value="<?php echo $this->untrimestre[0]['tresId'] ?>" />

                        <br>
                        <br>
                        
                            <div class="form-group">
                                <label class="col-md-6 control-label">Número Documento de la Persona <sup class="text-danger">*</sup></label>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="col-md-10"><input type="text" class="form-control" name="txtNombreTipo" id="txtNombreTipo" value="" /></div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-6 control-label">Nombre de la Persona<sup class="text-danger">*</sup></label>
                                <div class="col-md-6">
                                    <div class="col-md-12"><input type="text" class="form-control" name="txtNombreTipo" id="txtNombreTipo" value="" /></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6 control-label">Tipo De Sanción<sup class="text-danger">*</sup></label>
                                <div class="col-md-6">
                                    <div class="col-md-12"><input type="text" class="form-control" name="txtNombreTipo" id="txtNombreTipo" value="" /></div>
                                </div>
                            </div>
                           
                            <div class="form-group">
                                <label class="col-lg-6 control-label">Fecha de la Sanción <sup class="text-danger">*</sup></label>
                                <div class="col-md-6">
                                    <div class="col-md-12"><input type="date" class="form-control" name="txtFecha1" id="txtFecha1"  value="<?php echo $this->untrimestre[0]['tresFechaInicio'] ?>" />
                                    </div></div>
                            </div>
                        

                        

                        
                        


                                    


                                </div>
                            </div>
                        </div>
                </div>



                <div class="col-md-12">
                    <div class="form-group">
                        <div class="text-center">

                            <div class="modal bs-example-modal-sm" id="miventana<?php echo $i ?>" tabindex="-1" role="dialog" >
                                <div class="modal-dialog  ">
                                    <div class="modal-content">
                                        <div class="modal-header label-orange text-left">Mensaje de confirmación
                                            <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                        </div>
                                        <div class="modal-body">

                                            <h4>Deseas Realizar Formato salida ?</h4>
                                        </div>

                                        <div class="modal-footer discurso-enfatizado">
                                            <a class="btn btn-sm btn-success col-md-1 " href="<?php echo BASE_URL . 'pee-cefa/procesos/formatosalida/' ?>" role="button">Sí</a>
                                            <a class="btn btn-sm btn-danger col-md-1 " data-dismiss="modal" href="#" role="button">No</a>
                                        </div>
                                    </div>
                                </div>          
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-md-12 text-center">
                    <br>
                    <br>
                    <div class="form-group">
                        <div class="text-center">
                            <button class="btn btn-primary" data-toggle="modal" data-target="#miventana<?php echo $i ?>" >Guardar</button>
                            <a class="btn btn-danger" href="<?php echo BASE_URL . 'pee-cefa/reportes/pendientes'; ?>" >Cancelar</a>
                            <button type="button" class="btn btn-info" id="resetBtn">Limpiar</button>
                        </div>
                    </div>
                </div>
                </form>     
            </div>   
        </div>

    </div>
    <div class="col-md-2"></div>
</div>
</div>