<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Citas</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-sm-12">
                            <h3><?php echo $this->titulo ?></h3>
                        </div><br>

                        <div class="col-sm-12">
                            <a class="btn btn-sm btn-primary " href="<?php echo BASE_URL . 'agenda/buscar'; ?>" role="button">Volver</a>            
                            <div class="modal fade" id="miventana1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                            <h4>Esta seguro que desea Cancelar la Cita</h4>
                                        </div>
                                        <div class="modal-footer discurso-enfatizado">
                                            <a class="btn btn-sm btn-success " data-dismiss="modal" href="#" role="button">No</a>
                                            <a class="btn btn-sm btn-success " href="<?php echo BASE_URL . 'agenda/eliminar/' . $this->id; ?>" role="button">Sí</a>
                                        </div>
                                    </div>
                                </div>          
                            </div>
                        </div>
                        <br>
                        <div class="col-md-8  col-md-offset-2">
                            <?php if (isset($this->datos) && count($this->datos)): ?>

                            <div class="col-md-12">
                                <div class="col-md-4 label-custom">Id</div>
                                <div class="col-md-8"><?php echo $this->datos[0]['Id'] ?></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-4 label-custom">Mesa</div>
                                <div class="col-md-8"><?php echo $this->datos[0]['Mesa'] ?></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-4 label-custom">Hora</div>
                                <div class="col-md-8"><?php echo $this->datos[0]['Hora'] ?></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-4 label-custom">Comprador</div>
                                <div class="col-md-8"><?php echo $this->datos[0]['NomC'] ?></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-4 label-custom">Vendedor</div>
                                <div class="col-md-8"><?php echo $this->datos[0]['NomV'] ?></div>
                            </div>

                            <div class="col-md-12">
                                <div class="col-md-4 label-custom">Estado</div>
                                <div class="col-md-8"><?php echo $this->datos[0]['Estado'] ?></div>
                            </div>

                            <div class="col-md-12 text-center">
                                <br>
                                <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#miventana1">Cancelar Cita</button>
                            </div>
                            <?php else: ?>

                            <p><strong>No hay Citas a Cancelar!</strong></p>

                            <?php  endif; ?>                             

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>