<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Agenda</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-sm-12">
                            <h3><?php echo $this->titulo ?></h3>
                        </div><br>
                        <div class="col-sm-12">
                            <a class="btn btn-sm btn-primary " href="<?php echo BASE_URL . 'agenda/buscar'; ?>" role="button">Volver</a>
                            <div class="modal fade" id="miventana1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                            <h4>Esta seguro que desea editarlo</h4>
                                        </div>

                                        <div class="modal-footer discurso-enfatizado">
                                            <a class="btn btn-sm btn-success " data-dismiss="modal" href="#" role="button">No</a>
                                            <button class="btn btn-sm btn-success " type="button" onclick="document.form1.submit()"  >Sí</button>
                                        </div>
                                    </div>
                                </div>          
                            </div>
                        </div>
                        <br>
                        <div class="col-md-8  col-md-offset-2">
                            <?php if (isset($this->datos) && count($this->datos)): ?>
                                <form name="form1" id="form1" action="<?php echo BASE_URL . 'agenda/modificar/' . $this->id; ?>" method="POST">
                                    <div class="col-md-12">

                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Id</div>
                                            <div class="col-md-8"><?php echo $this->datos[0]['Id'] ?></div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Mesa</div>
                                            <div class="col-md-8">
                                                <select class="form-control" name="cmbMesa">
                                                    <option value="">Mesa</option>
                                                    <?php
                                                    for ($i = 1; $i <= $this->param[0]['Mesas']; $i++) {
                                                        $sel = '';
                                                        if ($this->datos[0]['Mesa'] == $i)
                                                            $sel = ' selected ';
                                                            ?>
                                                        <option value="<?php echo $i ?>" <?php echo $sel ?>>Mesa <?php echo $i ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Hora</div>
                                            <div class="col-md-8">
                                                <select class="form-control"  name="cmbHora">
                                                    <option value="">Hora</option>
                                                    <?php
                                                    for ($i = 0; $i < count($this->horas); $i++) {
                                                        $sel = '';
                                                        if ($this->datos[0]['Hora'] == $this->horas[$i]['Hora'])
                                                            $sel = ' selected ';
                                                            ?>
                                                        <option value="<?php echo $this->horas[$i]['Hora'] ?>" <?php echo $sel ?>><?php echo $this->horas[$i]['Hora'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Comprador</div>
                                            <div class="col-md-8">
                                                <select class="form-control" name="cmbComprador">
                                                    <option value="">Comprador</option>
                                                    <?php
                                                    for ($i = 0; $i < count($this->compra); $i++) {
                                                        $sel = '';
                                                        if ($this->datos[0]['NitC'] == $this->compra[$i]['Nit'])
                                                            $sel = ' selected ';
                                                            ?>
                                                        <option value="<?php echo $this->compra[$i]['Nit'] ?>" <?php echo $sel ?>><?php echo $this->compra[$i]['Nombre'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Vendedor</div>
                                            <div class="col-md-8"><select class="form-control" name="cmbVendedor">
                                                    <option value="">Vendedor</option>
                                                    <?php
                                                    for ($i = 0; $i < count($this->vende); $i++) {
                                                        $sel = '';
                                                        if ($this->datos[0]['NitV'] == $this->vende[$i]['Nit'])
                                                            $sel = ' selected ';
                                                            ?>
                                                        <option value="<?php echo $this->vende[$i]['Nit'] ?>" <?php echo $sel ?>><?php echo $this->vende[$i]['Nombre'] ?></option>
    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Estado</div>
                                            <div class="col-md-8">
                                                <select class="form-control" name="cmbEstado">
                                                    <option value="">Estado</option>
                                                    <?php if ($this->datos[0]['Estado'] == 'Pendiente') { ?>
                                                        <option value="Pendiente" selected>Pendiente</option> 
                                                    <?php } else {
                                                        ?>
                                                        <option value="Pendiente">Pendiente</option>
                                                    <?php }
                                                     if ($this->datos[0]['Estado'] == 'Activa') { ?>
                                                        <option value="Activa" selected>Activa</option> 
                                                    <?php } else {
                                                        ?>
                                                        <option value="Activa">Activa</option>
                                                    <?php }
                                                     if ($this->datos[0]['Estado'] == 'Finalizada') { ?>
                                                        <option value="Finalizada" selected>Finalizada</option> 
                                                    <?php } else {
                                                        ?>
                                                        <option value="Finalizada">Finalizada</option>
                                                    <?php }
                                                     if ($this->datos[0]['Estado'] == 'Cancelada') { ?>
                                                        <option value="Cancelada" selected>Cancelada</option> 
                                                    <?php } else {
                                                        ?>
                                                        <option value="Cancelada">Cancelada</option>
                                                    <?php }
                                                    ?>
                                                </select>
                                            </div>
                                        </div>

                                    </div>
                                </form>
                                <div class="col-md-12 text-center">
                                    <br>
                                    <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#miventana1">Guardar</button>
                                </div>                <?php else: ?>

                                <p><strong>No hay Citas a Modificar!</strong></p>
<?php endif; ?>                             

                        </div>

                    </div>
                </div>
            </div>        
        </div>
    </div>
</div>
