<style type="text/css">
    #scroll {
        height: 400px;
        overflow-y:scroll;
    }

</style>
<div class="container col-md-12">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Gestionar Agenda Ultimo Minuto</h3>
                    </div>
                    <div class="panel-body">
                        <form name="form1" method="post" action=""> 
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3 text-center">
                                    <h4><label>Filtrar por Categoria</label>
                                        <select name="cmbCategoria" onchange="form1.submit()">
                                            <option value="">Categoria</option>
                                            <?php
                                            for ($i = 0; $i < count($this->categorias); $i++):
                                                $sel = '';
                                                if ($_POST['cmbCategoria'] == $this->categorias[$i]['Id'])
                                                    $sel = ' selected ';
                                                ?>

                                                <option value="<?php echo $this->categorias[$i]['Id'] ?>" <?php echo $sel ?>><?php echo $this->categorias[$i]['Nombre'] ?></option>
                                            <?php endfor; ?>
                                        </select></h4>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="table-bordered col-md-6 text-center label-custom-back">
                                        <div class="col-md-12">
                                            <label class="label-custom">Empresas Compradoras</label>
                                        </div>

                                    </div>
                                    <div class="table-bordered col-md-6 text-center label-custom-back">
                                        <div class="col-md-12">
                                            <label class="label-custom">Empresas Vendedoras</label>
                                        </div>

                                    </div>
                                    <!-- Primera Columna -->
                                    <div id="scroll" class="col-sm-6 table-bordered">
                                        <?php for ($i = 0; $i < count($this->compra); $i++) { ?> 
                                            <div id="caja" class="row table-bordered">
                                                <div class="col-sm-12">

                                                    <label class="label-custom  text-uppercase">
                                                        <input type="checkbox" name="com" value="<?php echo $this->compra[$i]['Nit'] ?>">
                                                        <?php echo $this->compra[$i]['Nombre'] ?></label>
                                                </div>
                                                <div class="col-sm-12"><h6><strong><?php echo $this->compra[$i]['SectorEconomico'] ?></strong></h6></div>
                                                <div class="row">

                                                    <div class="col-sm-12">
                                                        <?php for ($j = 0; $j < count($this->intencion[$this->compra[$i]['Nit']]); $j++) { ?>
                                                            <div class="col-sm-12 text-lowercase">- <?php echo $this->intencion[$this->compra[$i]['Nit']][$j]['Nombre'] ?></div>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php } ?>
                                    </div>
                                    <!-- Segunda Columna -->

                                    <div id="scroll" class="col-md-6 table-bordered">
                                        <?php for ($i = 0; $i < count($this->vende); $i++) { ?>
                                            <div id="caja" class="row table-bordered">
                                                <div class="col-sm-12">
                                                    <label class="label-custom text-uppercase">
                                                        <input type="checkbox" name="ven" value="<?php echo $this->vende[$i]['Nit'] ?>">
                                                        <?php echo $this->vende[$i]['Nombre'] ?></label>
                                                </div>
                                                <?php for ($j = 0; $j < count($this->productos[$this->vende[$i]['Nit']]); $j++) { ?>
                                                    <div class="row">
                                                        <div class="col-sm-6">
                                                            <div class="col-sm-12 text-lowercase">- <?php echo $this->productos[$this->vende[$i]['Nit']][$j]['NomCat'] ?></div>
                                                        </div>
                                                        <div class="col-sm-6">
                                                            <div class="col-sm-12 text-lowercase">- <?php echo $this->productos[$this->vende[$i]['Nit']][$j]['NomPro'] ?></div>
                                                        </div></div>
                                                <?php } ?>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-4 col-md-offset-4">
                                    <button class="btn btn-lg btn-warning btn-block" type="submit">Cita rapida</button>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-4 col-md-offset-4">
                                    <button class="btn btn-lg btn-primary btn-block" type="submit">Verificar Disponibilidad</button>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-10 col-md-offset-1">
                                    <div class="row">
                                        <div  class="col-md-3 text-right label-custom"><strong>Nro Mesa</strong></div>
                                        <div  class="col-md-3 "><input name="txtMesas"  class="text-center" type="text" size="10px" value="1"></div>
                                        <div  class="col-md-3 text-right label-custom"><strong>Hora Cita</strong></div>
                                        <div  class="col-md-3 "><input name="txtInicioTH" class="text-center" type="text" size="1" value="10">
                                            <strong>:</strong> <input name="txtInicioTM" class="text-center" type="text" size="1" value="40">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-4 col-md-offset-4">
                                    <button class="btn btn-lg btn-custom btn-block" type="submit">Guardar Cita</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>        

</div>


