<style type="text/css">
    .vert { /* wider than clip to position buttons to side */
        margin-top: 0em;
        margin-bottom: 0em;
    }
    .vert .simply-scroll-clip {
        height: 40px;
    }
    .vert .simply-scroll-list li {
        height: 40px;
    }
    #mesa{
        border: double;
        border-radius:5px;
        border-color: #59B548 ;
    }

</style>
<?php
$col = $this->datos[0] ['Cols'];
$mes = $this->datos[0] ['Mesas'];
if (isset($col) && $col == 2) {
    $clasecolumna = "col-md-6";
    $h = 2;
} elseif (isset($col) && $col == 4) {
    $clasecolumna = "col-md-3";
    $h = 2;
} elseif (isset($col) && $col == 5) {
    $clasecolumna = "col-md-5ths";
    $h = 3;
    ?>
    <style type="text/css">
        #mesa .row{
            font-size: 9.5px;
        }
        .vert .simply-scroll-clip {
            height: 30px;
        }
        .vert .simply-scroll-list li {
            height: 30px;
        }
    </style>
    <?php
} else {
    $clasecolumna = "col-md-4";
        $h=2;
}
?>

<div class="container col-md-12">
    <div class="contenedor ">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Agenda Participantes Rueda de Negocios</h3>
                    </div>
                    <div class="panel-body">

                        <script type="text/javascript">
                            (function($) {
                                $(function() {
<?php for ($nm = 1; $nm <= $mes; $nm++) { ?>
                                        $("#scroller<?php echo $nm ?>").simplyScroll({
                                            orientation: 'vertical',
                                            customClass: 'vert',
                                            speed: 1,
                                        });
<?php } ?>
                                });
                            })(jQuery);
                        </script>
                        <!-- Primera Mesa -->
                        <?php for ($m = 1; $m <= $mes; $m++) { ?>
                            <div id="mesa" class="<?php echo $clasecolumna ?> table-bordered">
                                <div class="row">
                                    <div class="col-md-2">
                                        <div class="row text-center label-custom-clear-orange">Mesa <h<?php echo $h ?>><?php echo $m ?></h<?php echo $h ?>></div>
                                    </div>
                                    <div class="col-md-10 ">
                                        <div class="row table-bordered label-custom-clear-green">
                                            <div class="col-md-2">
                                                <div class="row text-center"><strong>10:00 am</strong></div>
                                            </div>
                                            <div class="col-md-10">
                                                <div class="row">
                                                    <div class="col-md-12"><strong>Comprador</strong></div>
                                                    <div class="col-md-12"><strong>Vendedor</strong></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="row text-center"></div>
                                    </div>    
                                    <div class="col-md-10">
                                        <div class="row">   
                                            <ul id="scroller<?php echo $m ?>">
                                                <li class="table-bordered">
                                                    <div class="col-md-2">
                                                        <div class="row text-center">10:20</div>
                                                    </div>
                                                    <div class="col-md-10">
                                                        <div class="row">
                                                            <div class="col-md-12">Comprador</div>
                                                            <div class="col-md-12">Vendedor</div>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li class="table-bordered">
                                                    <div class="col-md-2">
                                                        <div class="row text-center">10:40</div>
                                                    </div>
                                                    <div class="col-md-10">
                                                        <div class="row">
                                                            <div class="col-md-12">Comprador</div>
                                                            <div class="col-md-12">Vendedor</div>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li class="table-bordered">
                                                    <div class="col-md-2">
                                                        <div class="row text-center">11:00</div>
                                                    </div>
                                                    <div class="col-md-10">
                                                        <div class="row">
                                                            <div class="col-md-12">Comprador</div>
                                                            <div class="col-md-12">Vendedor</div>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div></div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>        
</div>

