<meta http-equiv="refresh" content="20" />
<style type="text/css">
    .vert { /* wider than clip to position buttons to side */
        margin-top: 0em;
        margin-bottom: 0em;
    }
    .vert .simply-scroll-clip {
        height: 40px;
    }
    .vert .simply-scroll-list li {
        height: 40px;
    }
    #mesa{
        border: double;
        border-radius:5px;
        border-color: #59B548 ;
    }
    #texto{
        font-size: 14px;
    }

</style>
<?php
$col = $this->datos[0] ['Cols'];
$mes = $this->datos[0] ['Mesas'];
if (isset($col) && $col == 2) {
    $clasecolumna = "col-md-6";
    $h = 2;
} elseif (isset($col) && $col == 4) {
    $clasecolumna = "col-md-3";
    $h = 2;
} elseif (isset($col) && $col == 5) {
    $clasecolumna = "col-md-5ths";
    $h = 3;
    ?>
    <style type="text/css">
        #mesa .row{
            font-size: 9.5px;
        }
        .vert .simply-scroll-clip {
            height: 30px;
        }
        .vert .simply-scroll-list li {
            height: 30px;
        }
    </style>
    <?php
} else {
    $clasecolumna = "col-md-4";
    $h = 2;
}
?>

<div class="container col-md-12">
    <div class="contenedor ">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Agenda Participantes Rueda de Negocios</h3>
                    </div>
                    <div class="panel-body">
                        <?php //print_r($this->citas); ?>
                        <script type="text/javascript">
                            (function($) {
                                $(function() {
<?php for ($nm = 1; $nm <= $mes; $nm++) { ?>
                                        $("#scroller<?php echo $nm ?>").simplyScroll({
                                            orientation: 'vertical',
                                            customClass: 'vert',
                                            speed: 1,
                                        });
<?php } ?>
                                });
                            })(jQuery);
                        </script>
                        <!-- Primera Mesa -->
                        <?php for ($m = 1; $m <= $mes; $m++) { ?>
                            <div id="mesa" class="<?php echo $clasecolumna ?> table-bordered">
                                <div class="row">
                                    <div class="col-md-2">
                                        <div class="row text-center label-custom-clear-orange">Mesa <h<?php echo $h ?>><?php echo $m ?></h<?php echo $h ?>></div>
                                    </div>
                                    <div class="col-md-10 ">
                                        
                                        <div class="row table-bordered label-custom-clear-green">
                                            <div class="col-md-2">
                                                <div class="row text-center"><strong>
                                                  <?php $st=0;
                                                  for ($j = 0; $j < count($this->horas); $j++) { 
                                                    if(isset($this->citas[$m][$this->horas[$j]['Hora']][4])){
                                                        if ($this->citas[$m][$this->horas[$j]['Hora']][4]=='Activa'){      
                                                       echo substr($this->citas[$m][$this->horas[$j]['Hora']][1],0,20);
                                                       $st=$st+1;
                                                    }else{ if ($st==0){echo '&nbsp;';}} }}?>
                                                    
                                                    </strong></div>
                                            </div>
                                            <div class="col-md-10">
                                                <div class="row">
                                                    <div class="col-md-12"><strong>
                                                        <?php $st=0; for ($j = 0; $j < count($this->horas); $j++) { 
                                                    if(isset($this->citas[$m][$this->horas[$j]['Hora']][4])){
                                                        if ($this->citas[$m][$this->horas[$j]['Hora']][4]=='Activa'){      
                                                       echo $this->citas[$m][$this->horas[$j]['Hora']][2];
                                                    $st=$st+1;}
                                                    else{
                                                    if ($st==0){echo '&nbsp;';}}
                                                        }}?>
                                                        </strong></div>
                                                            <div class="col-md-12"><strong>
                                                        <?php $st=0; for ($j = 0; $j < count($this->horas); $j++) { 
                                                    if(isset($this->citas[$m][$this->horas[$j]['Hora']][4])){
                                                        if ($this->citas[$m][$this->horas[$j]['Hora']][4]=='Activa'){      
                                                       echo substr($this->citas[$m][$this->horas[$j]['Hora']][3],0,20);
                                                    $st=$st+1;} 
                                                    else{
                                                        if ($st==0){echo '&nbsp;';}
                                                    }
                                                        }}?>
                                                        </strong></div>
                                                </div>
                                            </div>
                                        </div>
                                                    
                                    </div>
                                    <div class="col-md-2">
                                        <div class="row text-center"></div>
                                    </div>    
                                    <div class="col-md-10">
                                        <div class="row">   
                                            <ul id="scroller<?php echo $m ?>">
                                                <?php for ($j = 0; $j < count($this->horas); $j++) { 
                                                    if(isset($this->citas[$m][$this->horas[$j]['Hora']][2])){?>
                                                <li class="table-bordered">
                                                    <div class="col-md-2">
                                                        <div class="row text-center"><?php echo $this->horas[$j]['Hora'] ?></div>
                                                    </div>
                                                    <div class="col-md-10">
                                                        <div class="row">
                                                            <div id="texto" class="col-md-12 text-lowercase"><spam class="glyphicon glyphicon-usd text-success"></spam> <?php if(isset($this->citas[$m][$this->horas[$j]['Hora']][2])){echo substr($this->citas[$m][$this->horas[$j]['Hora']][2], 0, 30);}else{echo '-';}?></div>
                                                            <div id="texto" class="col-md-12 text-lowercase"><spam class="glyphicon glyphicon-briefcase text-primary"></spam> <?php if(isset($this->citas[$m][$this->horas[$j]['Hora']][3])){echo substr($this->citas[$m][$this->horas[$j]['Hora']][3], 0, 30);}else{echo '-';}?></div>
                                                        </div>
                                                    </div>
                                                </li>
                                                    <?php }}?>
                                            </ul>
                                        </div></div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>        
</div>

