<div class="container">
    <div class="contenedor">
        <h2>EVALUACION AL VENDEDOR</h2>
        <div class="contenedor panel panel-success">
            <div class="panel-heading">

                <h2>Datos del Comprador y Vendedor</h2>

                <div class="panel-body ">

                    <div class="col-md-12">

                        <div class="col-md-2">

                            <div class="table-bordered row text-center ">
                                <label>Mesa</label>
                                <label><?php echo $this->datos[0] ['Mesa']; ?></label>
                            </div>
                            <div class="table-bordered row text-center">
                                <label>Hora:</label>
                                <label><?php echo $this->datos[0] ['Hora']; ?></label>
                            </div>

                        </div>
                        <div class="col-md-5 table-bordered ">
                            <div class=" row table-bordered text-center">
                                <label class="">Comprador</label>
                            </div>
                            <?php if (isset($this->datos) && count($this->datos)): ?>


                                <div class="">
                                    <label><?php echo $this->datos[0] ['Nom1']; ?></label>
                                </div>

                                <div class="">
                                    <label class="text-left">NIT:</label>
                                    <label><?php echo $this->datos[0] ['Nit1']; ?></label>
                                </div>
                                <div class="">
                                    <label class=" text-left">Correo:</label>
                                    <label class=""><?php echo $this->datos[0] ['Cor1']; ?></label>
                                </div>

                                <div class="">
                                    <label class="">Telefono:</label>
                                    <label class=""><?php echo $this->datos[0] ['Tel1']; ?></label>
                                </div>

                            <?php else: ?>

                                <p><strong>No hay Evento!</strong></p>

                            <?php endif; ?>                             


                        </div>

                        <div class="col-md-5 table-bordered ">
                            <div class=" row table-bordered text-center">
                                <label class="">Vendedor</label>

                            </div>
                            <?php if (isset($this->datos) && count($this->datos[0])): ?>
                                <div class="">
                                    <label><?php echo $this->datos[0] ['Nom2']; ?></label>
                                </div>
                                <div class="">
                                    <label class="text-left">NIT:</label>
                                    <label><?php echo $this->datos[0] ['Nit2']; ?></label>
                                </div>
                                <div class="">
                                    <label class=" text-left">Correo:</label>
                                    <label class=""><?php echo $this->datos[0] ['Cor2']; ?></label>
                                </div>
                                <div class="">
                                    <label class="">Telefono:</label>
                                    <label class=""><?php echo $this->datos[0] ['Tel2']; ?></label>
                                </div>
                            <?php endif; ?>    
                        </div>

                    </div>
                    <form class="" data-toggle="modal"role="form" action="<?php echo BASE_URL . 'negociacion/guardar'; ?>" method="POST">  
                        <h2>Negociación</h2>

                        <div class="panel-body ">
                            <table id="mainTable" class="table table-hover  table-sdiviped">
                                <div>
                                    <div class=" col-md-12 label-success ">
                                        <label class="col-md-3 ">Nombre Producto</label>
                                        <label class="col-md-3 ">Expectativas de negocios generadas ($pesos colombianos)</label>
                                        <label class="col-md-3 ">Valor en Letras:</label>
                                        <label class="col-md-3 ">Expectativa Ejecucion del Negocio</label>
                                        <input name="numcat" type="hidden" value="<?php echo count($this->productos) ?>">
                                    </div>
                                </div>
                                <?php
                                for ($i = 0; $i < count($this->productos); $i++):
                                    ?>

                                    <div class=" table-bordered">
                                        <div class="row">
                                            <label class = "col-md-3" value = "" id = ""><input type = "hidden" name = "idproducto<?php echo $i ?>" value="<?php echo $this->productos[$i]['Id']; ?>"><?php echo $this->productos[$i] ['Nombre']; ?>
                                            </label>
                                            <label class="col-md-3 "><input class="col-md-12 text-right" placeholder="$" name="precio<?php echo $i ?>" id="numero<?php echo $i ?>" onkeyup="document.getElementById('letra<?php echo $i ?>').innerHTML = nt(document.getElementById('numero<?php echo $i ?>').value)" maxlength="10" size="10" required /></label>
                                            <h6><label class="col-md-3" ><div name="letra[]" id="letra<?php echo $i ?>"></div></label></h6>
                                            <label class="col-md-3"><input  type="radio" name="<?php echo $i ?>" value="0-3 meses" required="" /><label>0-3 meses</label>&ThinSpace;&ThinSpace;&ThinSpace;&ThinSpace;&ThinSpace;<input  type="radio" name="<?php echo $i ?>" value="3meses" required /><label>Mas de 3 meses</label></label>
                                        </div>
                                    </div>

                                <?php endfor; ?>
                            </table>
                        </div>

                        <h2>Evaluación</h2>
                        <div class="col-md-12">


                            <div class="label-success row text-center table-bordered">
                                <label class="label-success col-md-7 ">Evaluación Al Vendedor</label>
                                <label class="label-success col-md-1 ">Excelente</label>
                                <label class="label-success col-md-1 ">Bueno</label>
                                <label class="label-success col-md-1 ">Aceptable</label>
                                <label class="label-success col-md-1 ">Deficiente</label>
                                <label class="label-success col-md-1 ">Malo</label>
                            </div>


                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left">Conocimiento de su negocio y claridad para presentarlo</label>
                                <label class=" col-md-1"><input  type="radio" name="rb1" value="5" required/></label>
                                <label class="col-md-1"><input  type="radio" name="rb1" value="4" required/></label>
                                <label class="col-md-1"><input  type="radio" name="rb1" value="3" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb1" value="2" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb1" value="1" required/></label>

                            </div>

                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left">Habilidad en la Negociación</label>
                                <label class=" col-md-1"><input  type="radio" name="rb2" value="5" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb2" value=4 required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb2" value="3" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb2" value="2" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb2" value="1" required/></label>

                            </div>

                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left">Empoderamiento(capacidad para tomar desiciones)</label>
                                <label class=" col-md-1"><input  type="radio" name="rb3" value="5" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb3" value="4" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb3" value="3" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb3" value="2" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb3" value="1" required/></label>

                            </div>

                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left">Capacidad Para generar confianza</label>
                                <label class=" col-md-1"><input  type="radio" name="rb4" value="5" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb4" value="4" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb4" value="3" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb4" value="2" required/></label>
                                <label class=" col-md-1"><input  type="radio" name="rb4" value="1" required/></label>

                            </div>
                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left">Relación costo-beneficio del Producto y/o servicio (precio frente a la calidad)</label>
                                <label class=" col-md-1"><input  type="radio" name="rb5" value="5" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb5" value="4" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb5" value="3" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb5" value="2" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb5" value="1" required /></label>

                            </div>
                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left">Calidad de Productos y/o Servicios</label>
                                <label class=" col-md-1"><input  type="radio" name="rb6" value="5" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb6" value="4" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb6" value="3" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb6" value="2" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb6" value="1" required /></label>
                            </div>
                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left">Diferenciación del producto y/o (¿Qué tan diferente/único es?</label>
                                <label class=" col-md-1"><input  type="radio" name="rb7" value="5" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb7" value="4" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb7" value="3" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb7" value="2" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb7" value="1" required /></label>
                            </div>
                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left">Razonabilidad de los tiempos de entrega</label>
                                <label class=" col-md-1"><input  type="radio" name="rb8" value="5" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb8" value="4" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb8" value="3" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb8" value="2" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb8" value="1" required /></label>
                            </div>

                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left">Volumen y tiempos de entrega</label>
                                <label class=" col-md-1"><input  type="radio" name="rb9" value="5" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb9" value="4" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb9" value="3" required /></label>
                                <label class=" col-md-1" ><input  type="radio" name="rb9" value="2" required /></label>
                                <label class=" col-md-1"><input  type="radio" name="rb9" value="1" required /></label>
                            </div>
                            <div class="row text-center table-bordered">
                                <label class=" col-md-7 text-left ">Capacidad logística para llevar el producto o prestar el servicio donde sea requerido</label>
                                <label class=" col-md-1 "><input  type="radio" name="rb10" value="5" required /></label>
                                <label class=" col-md-1 "><input  type="radio" name="rb10" value="4" required /></label>
                                <label class=" col-md-1 "><input  type="radio" name="rb10" value="3" required /></label>
                                <label class=" col-md-1 "><input  type="radio" name="rb10" value="2" required /></label>
                                <label class=" col-md-1 "><input  type="radio" name="rb10" value="1" required /></label>
                            </div>
                            <div>
                                <button class=" btn btn-success text-center" type="submit">Guardar calificación</button>
                            </div>
                        </div>
                    </form>    
                </div>       

            </div>
        </div>
    </div>
</div>