<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <br>
                    <div class="row ">
                    <div class="col-md-8 col-md-offset-2 label-custom-clear-green btn">
                        <div class="row">
                            <div class="col-md-3">Mesa</div><div class="col-md-3">Hora</div><div class="col-md-6">Comprador: <strong class="text-uppercase"><?php echo $this->datos[0]['Nom1'] ?></strong></div>
                        </div>
                        <div class="row">
                            <div class="col-md-3"><strong><?php echo $this->datos[0]['Mesa'] ?></strong></div><div class="col-md-3"><strong><?php echo $this->datos[0]['Hora'] ?></strong></div><div class="col-md-6">Vendedor: <strong class="text-uppercase"><?php echo $this->datos[0]['Nom2'] ?></strong></div>
                        </div>
                    </div>                        
                        
                    </div>

                    <div class="panel-body">
                        <div class="col-md-6 col-md-offset-3">

                            <div class="text-center label-custom">
                                <h2>Tiempo Restante</h2>

                            </div>
                            <div class="panel-body contenedor">
                                <div class="text-center">
                                    <div class="clock" style="margin:2em;"></div>
                                    <div class="message"></div>


                                    <script type="text/javascript">
                                        var clock;
                                        var pagina;
                                        pagina = "<?php echo BASE_URL . 'negociacion/evaluacion'; ?>"
                                        function redireccionar()
                                        {
                                            location.href = pagina

                                        }

                                        $(document).ready(function() {

                                            clock = $('.clock').FlipClock(1080, {
                                                clockFace: 'MinuteCounter',
                                                countdown: true,
                                                autoStart: true,
                                                callbacks: {
                                                    start: function() {
                                                        $('.message').html('');
                                                        setTimeout("redireccionar()", 1115640);
                                                    }
                                                }
                                            });
                                        });

                                    </script>
                                </div>
                            </div>
 <br>
                            <div class="row text-center">
                                <div>
                                    <div >
                                        <button class="btn btn-success btn-lg"data-toggle="modal" data-target="#miventana1" href="#">Finalizar Cita</button>
                                        <div class="modal fade bs-example-modal-sm " id="miventana1" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                            <div class="modal-dialog ">
                                                <div class="modal-content">
                                                    <div class="modal-body">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                                        <h3>Esta Seguro Que Desea Terminar La Negociación</h3>
                                                    </div>

                                                    <div class="modal-footer discurso-enfatizado">
                                                        <a class="btn btn-sm btn-success " data-dismiss="modal" href="#" role="button">No</a>
                                                        <a class="btn btn-sm btn-success " href="<?php echo BASE_URL . 'negociacion/evaluacion'; ?>" role="button">Sí</a>
                                                    </div>
                                                </div>
                                            </div>          
                                        </div>
                                    </div>
                                </div>
                               
                                <br>
                                <div>
                                    <div id="">
                                        <a class="btn btn-danger " data-toggle="modal" data-target="#miventana2" href="#" role="button" style="margin-left: 10px">Cancelar Cita</a>
                                        <div class="modal fade" id="miventana2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-body">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                                        <h3>Esta Seguro Que Desea Cancelar la Cita</h3>
                                                    </div>

                                                    <div class="modal-footer discurso-enfatizado">
                                                        <a class="btn btn-sm btn-success " data-dismiss="modal" href="#" role="button">No</a>
                                                        <a class="btn btn-sm btn-success " href="<?php echo BASE_URL . 'negociacion/cancelar'; ?>" role="button">Sí</a>
                                                    </div>
                                                </div>
                                            </div>          
                                        </div>
                                    </div>
                                </div>      
                            </div>                           

                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </div>
</div>