<style type="text/css">
    .vert .simply-scroll-clip {
        height: 200px;
    }
    .vert .simply-scroll-list li {
        height: 40px;
    }
</style>
<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Informe Consolidado Rueda de Negocios</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-sm-12">
                            <div class="col-sm-4 text-right">
                                <label class="label-custom">Empresas Vendedoras</label>
                            </div>
                            <div class="col-sm-2">
                                <input class="text-center" size="10" value="1">                     
                            </div>
                            <div class="col-sm-4 text-right">
                                <label class="label-custom">Empresas Compradoras</label>
                            </div>
                            <div class="col-sm-2">
                                <input class="text-center" size="10" value="1">                        
                            </div>
                        </div>
                        <hr>
                        <div class="col-sm-12">
                            <div class="col-sm-4 text-right">
                                <label class="label-custom">Citas Programadas</label>
                            </div>
                            <div class="col-sm-2">
                                <input class="text-center" size="10" value="1">                        
                            </div>
                            <div class="col-sm-4 text-right">
                                <label class="label-custom">Contactos Realizados</label>
                            </div>
                            <div class="col-sm-2">
                                <input class="text-center" size="10" value="1">                        
                            </div>
                        </div>
                        <hr>
                        <br>

                        <div class="col-sm-12 text-center">
                            <label class="label-custom">NEGOCIOS LLEVADOS A FELIZ TERMINO</label>
                        </div>

                        <div class="table-bordered col-sm-12 text-center label-custom-back">
                            <div class="col-sm-4">
                                <label class="label-custom">Categoria</label>
                            </div>
                            <div class="col-sm-4">
                                <label class="label-custom">Cantidad</label>
                            </div>
                            <div class="col-sm-4">
                                <label class="label-custom">Valor</label>
                            </div>
                        </div>
                        <script type="text/javascript">
                            (function($) {
                                $(function() {
                                    $("#scroller").simplyScroll({
                                        orientation: 'vertical',
                                        customClass: 'vert',
                                        speed: 1,
                                    });
                                });
                            })(jQuery);
                        </script>
                        <div class="col-sm-12 table-bordered">
                            <ul id="scroller">
                                <li>
                                    <div>
                                        <div class="col-sm-6">
                                            <label class="label-custom">Categoria 1</label>
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-center" size="10" value="1">                     
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-right" size="10" value="1"> 
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <div class="col-sm-6">
                                            <label class="label-custom">Categoria 2</label>
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-center" size="10" value="1">                     
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-right" size="10" value="1"> 
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <div class="col-sm-6">
                                            <label class="label-custom">Categoria 3</label>
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-center" size="10" value="1">                     
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-right" size="10" value="1"> 
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <div class="col-sm-6">
                                            <label class="label-custom">Categoria 4</label>
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-center" size="10" value="1">                     
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-right" size="10" value="1"> 
                                        </div>
                                    </div>
                                </li>                                
                                <li>
                                    <div>
                                        <div class="col-sm-6">
                                            <label class="label-custom">Categoria 5</label>
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-center" size="10" value="1">                     
                                        </div>
                                        <div class="col-sm-3">
                                            <input class="text-right" size="10" value="1"> 
                                        </div>
                                    </div>
                                </li>                        
                            </ul>  
                        </div>

                        <br>&nbsp;
                        <div class="col-sm-12 text-center">
                            <div class="col-sm-8">
                                <label class="label-custom">Total Negociado</label>
                            </div>
                            <div class="col-sm-4">
                                <input class="text-right" size="10" value="1">
                            </div>
                        </div>
                        <br>&nbsp;
                        <div class="col-sm-12 text-center">
                            <div class="col-sm-6">
                                <input type="button" class="btn-custom" value="Descargar PDF">
                            </div>
                            <div class="col-sm-6">
                               <input class="text-left" size="25" value="" placeholder="Correo" ><input type="button" class="btn-custom" value="Enviar">
                            </div>
                        </div>           
                    </div>
                </div>

            </div>
        </div>
    </div>        

</div>
</div>
