<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="bs-example" data-example-id="carousel-with-captions">
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="1"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="2"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="3"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="4"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>pee1.jpg" alt="Prestamo De Equipo">
                                    <div class="carousel-caption">
                                        <h3>Prestamo De Equipos</h3>
                                        <p>Nota 1</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>pee2.jpg" alt="Unidad 2">
                                    <div class="carousel-caption">
                                        <h3>Cables HDMI</h3>
                                        <p>Nota 2</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>pee3.jpg" alt="Unidad 3">
                                    <div class="carousel-caption">
                                        <h3>Unidad 3</h3>
                                        <p>Nota 3</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>pee4.jpg" alt="Unidad 4">
                                    <div class="carousel-caption">
                                        <h3>Unidad 4</h3>
                                        <p>Nota 4</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>pee5.jpg" alt="Unidad 5">
                                    <div class="carousel-caption">
                                        <h3>Unidad 5</h3>
                                        <p>Nota 5</p>
                                    </div>
                                </div>
                                 <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>pee6.jpg" alt="Unidad 5">
                                    <div class="carousel-caption">
                                        <h3>Unidad 5</h3>
                                        <p>Nota 5</p>
                                    </div>
                                </div>
                                
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div><!-- /example -->
                </div>
            </div>
        </div>
        
        <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="label-orange">Bandeja de Entrada</div>
                </div>
                <div class="panel-body">
                    <a class="btn btn-link " href="<?php echo BASE_URL . 'pee-cefa/inicio/vencidos'; ?>" >Elementos </a>
                    <br>
                    <br>
                    <a class="btn btn-link " href="<?php echo BASE_URL . 'pee-cefa/procesos/sanciones'; ?>" >Personas Con Sus respectivas Sanciones</a>
                    <br>
                    <br>
                    <a class="btn btn-link " href="<?php echo BASE_URL . 'pee-cefa/procesos/prestamo'; ?>" >Elementos Y equipos Prestados</a>
                    
                   
                    
                    
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                <div class="label-orange"> PEE-CEFA (Prestamo de Equipos Y Elementos del Centro De Formacion Agroindustrial La Angostura)</div>
               </div>
                <div class="panel-body">
    
                    El   Sistema de información PEE-CEFA, se basa en  llevar acabo el   registro de los diferentes prestamos de equipos que se generan en el centro de formación Agroindustrial la Angostura, de manera Organizada, fiable,
                    clara, rápida, segura y eficaz. 
                    
                    El sistema de información PEE-CEFA es un sistema que está enmarcado para cumplir con las siguientes funciones:
                    <br>


                    <div>Gestionar la información relacionada con el préstamo de equipos y elementos de los diferentes ambientes de formación, UIT y ADSI.</div>

                    <div>Generar reportes de préstamos de equipos identificando que área los presta y quien es el responsable.</div>

                    <div>Generar reporte general del estado de los elementos y equipos.</div>

                    <div>Generar reportes de inventario</div>

                    <div>Generar sanciones por incumplimiento en la devolución de los elementos.</div>

                    Gestionar la información de inventario de los ambientes y unidades productivas.
                </div>
            </div>
        </div>
    
        </div>
    </div>
    </div>


