<?php
$_SESSION['autentificado']='';
$_SESSION['mensaje'] = '';
$_SESSION['tipomensaje'] = '';
$_SESSION['login'] = '';
?>
<div class="container">
    <div class="row col-md-4 col-md-offset-4 ">
        <div class="panel panel-success sombra">
            <div id="psesion" class="panel-heading">
                <h3 class="panel-title"><?php echo $this->titulo ?></h3>
            </div>

            <form class="form-signin" role="form" action="<?php echo BASE_URL . 'portal/sesion/ingresar'; ?>" method="POST">
                <div class="item text-center">
                    <img width="100%" src="<?php echo $_layoutParams['ruta_img']; ?>inicio.png">
                </div>
                <input name="txtUsuario" id="txtUsuario" type="text" class="form-control" placeholder="Usuario" required autofocus>
                <input name="txtPass" id="txtPass" type="password" class="form-control" placeholder="Clave" required>
                <?php if (isset($this->mensaje)) { ?>
                    <div class="alert alert-danger" role="alert">
                        <strong>Atencion! </strong> <?php echo $this->mensaje; ?> 
                    </div>
                <?php } ?>
                <button class="btn btn-lg btn-success btn-block" type="submit">Ingresar</button>
                <hr>
                <a class="btn btn-sm btn-default btn-block" href="<?php echo BASE_URL . 'portal/inicio/index'; ?>" role="button">Cancelar</a>
            </form>
        </div>
    </div>

</div> <!-- /container -->