<div class="container">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="panel panel-warning sombra">
            <div class="panel-heading"><h4 class="label-orange">Redes y Lineas Tecnológicas</h4></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <a class="btn  btn-sm btn-success" href="<?php echo BASE_URL . 'sigac/parametros/viewredeslineas'; ?>" >Agregar</a>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12  ">
                        <div class="table-responsive">
                            <table id="datatable" class="table table-condensed table-striped table-bordered table-hover">
                                <thead>
                                    <tr class="warning">
                                        <th>Id</th>
                                        <th>Red</th>
                                        <th>Linea</th>
                                        <th class="">Acciones</th>
                                    </tr>        
                                </thead>
                                <tbody>

                                    <?php
                                    $control = "";
                                    for ($i = 0; $i < count($this->redeslineas); $i++) {
                                        if ($i == 0 || $this->redeslineas[$i]['rdesId'] <> $control) {
                                            $control = $this->redeslineas[$i]['rdesId'];
                                            ?>
                                            <tr>                         
                                                <td class="text-center"><?php echo $this->redeslineas[$i]['rdesId'] ?></td>
                                                <td><?php echo $this->redeslineas[$i]['rdesNombre'] ?></td>
                                                <td><div><span class="glyphicon glyphicon-triangle-right text-muted " ></span> <?php echo $this->redeslineas[$i]['leasNombre'] ?></div>
                                                    <?php
                                                } else {
                                                    ?>
                                                    <div><span class="glyphicon glyphicon-triangle-right  text-muted" ></span> <?php echo $this->redeslineas[$i]['leasNombre'] ?></div>
                                                    <?php
                                                }
                                                if ($i == count($this->redeslineas) - 1) {
                                                    ?>
                                                </td>
                                                <td class="text-center">
                                                    <a class="btn btn-sm btn-warning" href="<?php echo BASE_URL . 'sigac/parametros/viewredeslineas/' . $this->redeslineas[$i]['rdesId']; ?>" title="Modificar" ><span class="glyphicon glyphicon-edit"></span></a>
                                                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#miventana<?php echo $i ?>" title="Eliminar" ><span class="glyphicon glyphicon-remove"></span></button>

                                                    <div class="modal bs-example-modal-sm" id="miventana<?php echo $i ?>" tabindex="-1" role="dialog" >
                                                        <div class="modal-dialog  ">
                                                            <div class="modal-content">
                                                                <div class="modal-header label-orange text-left">Mensaje de confirmación
                                                                    <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                                                </div>
                                                                <div class="modal-body">

                                                                    <h4>¿Esta Seguro de Eliminar el Registro <?php echo $this->redeslineas[$i]['rdesId'] ?>?</h4>
                                                                </div>

                                                                <div class="modal-footer discurso-enfatizado">
                                                                    <a class="btn btn-sm btn-success col-lg-1 " href="<?php echo BASE_URL . 'sigac/parametros/delredeslineas/' . $this->redeslineas[$i]['rdesId']; ?>" role="button">Sí</a>
                                                                    <a class="btn btn-sm btn-danger col-lg-1 " data-dismiss="modal" href="#" role="button">No</a>
                                                                </div>
                                                            </div>
                                                        </div>          
                                                    </div>
                                                </td>              
                                            </tr>
                                            <?php
                                        } else {
                                            if ($this->redeslineas[$i + 1]['rdesId'] <> $control) {
                                                ?>
                                                </td>
                                            <td class="text-center">
                                                <a class="btn btn-sm btn-warning" href="<?php echo BASE_URL . 'sigac/parametros/viewredeslineas/' . $this->redeslineas[$i]['rdesId']; ?>" title="Modificar" ><span class="glyphicon glyphicon-edit"></span></a>
                                                <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#miventana<?php echo $i ?>" title="Eliminar" ><span class="glyphicon glyphicon-remove"></span></button>

                                                <div class="modal bs-example-modal-sm" id="miventana<?php echo $i ?>" tabindex="-1" role="dialog" >
                                                    <div class="modal-dialog  ">
                                                        <div class="modal-content">
                                                            <div class="modal-header label-orange text-left">Mensaje de confirmación
                                                                <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                                            </div>
                                                            <div class="modal-body">

                                                                <h4>¿Esta Seguro de Eliminar el Registro <?php echo $this->redeslineas[$i]['rdesId'] ?>?</h4>
                                                            </div>

                                                            <div class="modal-footer discurso-enfatizado">
                                                                <a class="btn btn-sm btn-success col-lg-1 " href="<?php echo BASE_URL . 'sigac/parametros/delredeslineas/' . $this->redeslineas[$i]['rdesId']; ?>" role="button">Sí</a>
                                                                <a class="btn btn-sm btn-danger col-lg-1 " data-dismiss="modal" href="#" role="button">No</a>
                                                            </div>
                                                        </div>
                                                    </div>          
                                                </div>
                                            </td>              
                                            </tr>
                                            <?php
                                        }
                                    }
                                    ?>



                                <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>
</div>
