<div id="vista" class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange">Trimestres Academicos</h4></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <button id="btnAddTrimestre" class="btn btn-sm btn-success" >Agregar</button>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-12  ">
                            <div class="table-responsive">
                                <table id="datatable" class="dt-responsive table table-condensed table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                    <thead>
                                        <tr class="warning">
                                            <th>Id</th>
                                            <th>Trimestre</th>
                                            <th>Año</th>
                                            <th>Fecha Inicio</th>
                                            <th>Fecha Final</th>
                                            <th class="">Acciones</th>
                                        </tr>        
                                    </thead>
                                    <tbody>
                                        <?php for ($i = 0; $i < count($this->trimestres); $i++) {
                                            ?>
                                            <tr>                         

                                                <td class="text-center"><?php echo $this->trimestres[$i]['tresId'] ?></td>
                                                <td><?php echo $this->trimestres[$i]['tresNombre'] ?></td>
                                                <td class="text-center"><?php echo $this->trimestres[$i]['tresAnual'] ?></td>
                                                <td class="text-center"><?php echo Funcionesphp::MySQLDateToDate($this->trimestres[$i]['tresFechaInicio']) ?></td>
                                                <td class="text-center"><?php echo Funcionesphp::MySQLDateToDate($this->trimestres[$i]['tresFechaFin']) ?></td>
                                                <td class="text-center">
                                                    <button id="btnEditTrimestre" class="btn btn-sm btn-warning" title="Modificar" value="<?php echo $this->trimestres[$i]['tresId']; ?>" ><span class="glyphicon glyphicon-edit"></span></button>
                                                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modaltrimestre" data-whatever="<?php echo $this->trimestres[$i]['tresId']; ?>"  title="Eliminar" ><span class="glyphicon glyphicon-remove"></span></button>
                                                </td>              
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
    <div class="modal bs-example-modal-sm" id="modaltrimestre" tabindex="-1" role="dialog" >
        <div class="modal-dialog  ">
            <div class="modal-content">
                <div class="modal-header label-orange text-left">Mensaje de confirmación
                    <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                </div>
                <div class="modal-body">

                    <h4>¿?</h4>
                </div>

                <div class="modal-footer discurso-enfatizado">
                    <a id="enviar" class="btn btn-sm btn-success col-lg-1 " href="#" role="button">Sí</a>
                    <a class="btn btn-sm btn-danger col-lg-1 " data-dismiss="modal" href="#" role="button">No</a>
                </div>
            </div>
        </div>          
    </div>
</div>