<?php
if (isset($this->untrimestre)) {
    $id = $this->untrimestre[0]['tresId'];
    $nombre = $this->untrimestre[0]['tresNombre'];
    $anual = $this->untrimestre[0]['tresAnual'];
    $fecini = $this->untrimestre[0]['tresFechaInicio'];
    $fecfin = $this->untrimestre[0]['tresFechaFin'];
} else {
    $id = '';
    $nombre = '';
    $anual = '';
    $fecini = '';
    $fecfin = '';
}
?>
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange"><?php echo $this->titulopanel ?></h4></div>
                <div class="panel-body">
                    <form id="form1" name="form1" class="form-horizontal" method="post" action="<?php echo BASE_URL . 'sigac/parametros/savetrimestre'; ?>">
                        <input type="hidden"name="txtId" id="txtId" value="<?php echo $id ?>" />
                        <fieldset>
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Trimestre <sup class="text-danger">*</sup></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" name="txtNombreTipo" id="txtNombreTipo" value="<?php echo $nombre ?>" required />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Año <sup class="text-danger">*</sup></label>
                                <div class="col-lg-3">
                                    <input type="number" class="form-control" name="txtAnual" id="txtAnual" value="<?php echo $anual ?>" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Fecha Inicio <sup class="text-danger">*</sup></label>
                                <div class="col-lg-4">
                                    <input type="date" class="form-control" name="txtFecha1" id="txtFecha1"  value="<?php echo $fecini ?>" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Fecha Fin <sup class="text-danger">*</sup></label>
                                <div class="col-lg-4">
                                    <input type="date" class="form-control" name="txtFecha2" id="txtFecha2"  value="<?php echo $fecfin ?>" />
                                </div>
                            </div>

                        </fieldset>
                        <div class="form-group">
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary" id="btnGuardar">Guardar</button>
                                <a class="btn btn-danger" href="<?php echo BASE_URL . 'sigac/parametros/trimestre'; ?>" >Cancelar</a>
                                <button type="button" class="btn btn-info" id="resetBtn">Limpiar</button>
                            </div>
                        </div>
                    </form>     
                </div>   
            </div>

        </div>
        <div class="col-md-2"></div>
    </div>
</div>
