<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Padrinos</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-sm-12">
                            <h3><?php echo $this->titulo ?></h3>
                        </div><hr/>
                        <div class="col-sm-12" >
                            <a class="btn btn-sm btn-success " href="<?php echo BASE_URL . 'padrino/nuevo'; ?>" role="button">Nuevo Registro</a>
                            <a class="btn btn-sm btn-primary " href="<?php echo BASE_URL . 'padrino/buscar'; ?>" role="button">Buscar Registro</a>
                        </div>
                        <br>
                        <hr>
                        <?php if (isset($this->datos) && count($this->datos)): ?>
                            <div class="table-bordered col-sm-12 label-custom-back text-left">
                                <div class="col-sm-2"><label class="label-custom">Documento</label></div>
                                <div class="col-sm-3"><label class="label-custom">Nombre</label></div>
                                <div class="col-sm-2"><label class="label-custom">Telefono</label></div>
                                <div class="col-sm-3"><label class="label-custom">Correo</label></div>
                                <div class="col-sm-2"><label class="label-custom">Acciones</label></div>
                            </div>
                            <?php for ($i = 0; $i < count($this->datos); $i++): ?>
                                <div class="table-bordered col-sm-12">
                                    <div class="col-sm-2"><?php echo $this->datos[$i] ['Documento']; ?></div>
                                    <div class="col-sm-3"><?php echo $this->datos[$i] ['Nombre']; ?></div>
                                    <div class="col-sm-2"><?php echo $this->datos[$i] ['Telefono']; ?></div>
                                    <div class="col-sm-3"><?php echo $this->datos[$i] ['Correo']; ?></div>
                                    <div class="col-sm-2">
                                        <a class="col-sm-6 btn btn-sm btn-warning " href="<?php echo BASE_URL . 'padrino/editar/' . $this->datos[$i] ['Documento']; ?>" role="button">Editar</a>
                                        <a class="col-sm-6 btn btn-sm btn-danger" href="<?php echo BASE_URL . 'padrino/borrar/' . $this->datos[$i] ['Documento']; ?>" role="button">Borrar</a>
                                    </div>
                                </div>
                            <?php endfor; ?>
                        <?php else: ?>
                            <div class="col-sm-12">            
                                <p><strong>No hay Padrinos!</strong></p> 
                            </div>
                        <?php endif; ?>                

                    </div>
                </div>
            </div>
        </div>        
    </div>
</div>