<div class="container">
    <div class="hero-unit">

        <h1>Eventos<br/> <small><?php echo $this->titulo ?></small></h1>
        <hr/>
        <div>
            <a class="btn btn-sm btn-primary " href="<?php echo BASE_URL . 'evento/nuevo'; ?>" role="button">Nuevo Registro</a>
            <a class="btn btn-sm btn-primary " href="<?php echo BASE_URL . 'evento/buscar'; ?>" role="button">Buscar Registro</a>
        </div>
        <br>
        <div class="row">
            <div class="col-md-12">
                <?php if (isset($this->datos) && count($this->datos)): ?>

                    <table id="mainTable" class="table table-striped">
                        <thead>
                            <tr class="label-info">
                                <th>#</th>
                                <th>Nombre</th>
                                <th>Tipo</th>
                                <th>Inicio</th>
                                <th>Fin</th>
                                <th>Lugar</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>

                            <?php for ($i = 0; $i < count($this->datos); $i++): ?>
                                <tr>
                                    <td><?php echo $this->datos[$i] ['IdEvento']; ?></td>
                                    <td><?php echo $this->datos[$i] ['Nombre']; ?></td>
                                    <td><?php echo $this->datos[$i] ['TipoEvento']; ?></td>
                                    <td><?php echo $this->datos[$i] ['FInicio']; ?></td>
                                    <td><?php echo $this->datos[$i] ['FFin']; ?></td>
                                    <td><?php echo $this->datos[$i] ['Lugar']; ?></td>
                                    <td>
                                        <a class="btn btn-sm btn-success " href="<?php echo BASE_URL . 'evento/ver/'.$this->datos[$i] ['IdEvento']; ?>" role="button">Ver</a>
                                        &ThinSpace;<a class="btn btn-sm btn-warning " href="<?php echo BASE_URL . 'evento/editar/'.$this->datos[$i] ['IdEvento']; ?>" role="button">Editar</a>
                                        &ThinSpace;<a class="btn btn-sm btn-danger" href="<?php echo BASE_URL . 'evento/borrar/'.$this->datos[$i] ['IdEvento']; ?>" role="button">Borrar</a>
                                    </td>
                                </tr>
                            <?php endfor; ?>
                        </tbody>
                    </table>

                <?php else: ?>

                    <p><strong>No hay Eventos!</strong></p>

                <?php endif; ?>                

            </div>
        </div>

    </div>
</div>