<div class="container">
    <div class="hero-unit">

        <h1>Eventos<br/> <small><?php echo $this->titulo ?></small></h1>
        <hr/>
        <div>
            <a class="btn btn-sm btn-primary " href="<?php echo BASE_URL . 'evento/index'; ?>" role="button">Volver</a>
        </div>
        <br>
        <div class="row">
            <div class="col-md-6">
                <?php if (isset($this->datos) && count($this->datos)): ?>

                    <table id="mainTable" class="table table-bordered">
                        <tbody>      
                            <tr>
                                <th class="label-info">#</th>
                                <td class=""><?php echo $this->datos[0] ['IdEvento']; ?></td>
                            </tr>
                            <tr>
                                <th class="label-info">Nombre del Evento</th>
                                <td><?php echo $this->datos[0] ['Nombre']; ?></td>
                            </tr>
                            <tr>
                                <th class="label-info">Tipo de Evento</th>
                                <td><?php echo $this->datos[0] ['TipoEvento']; ?></td>
                            </tr>
                            <tr>
                                <th class="label-info">Fecha y Hora de Inicio</th>
                                <td><?php echo $this->datos[0] ['FInicio']; ?></td>
                            </tr>
                            <tr>
                                <th class="label-info">Fecha y Hora de Finalización</th>
                                <td><?php echo $this->datos[0] ['FFin']; ?></td>
                            </tr>
                            <tr>
                                <th class="label-info">Lugar</th>
                                <td><?php echo $this->datos[0] ['Lugar']; ?></td>
                            </tr>                            
                            <tr>
                                <th class="label-info">Encargado</th>
                                <td><?php echo $this->datos[0] ['NombreE']; ?></td>
                            </tr>
                            <tr>
                                <th class="label-info">Cant Max Participante</th>
                                <td><?php echo $this->datos[0] ['CantMaxiAsis']; ?></td>
                            </tr>
                            <tr>
                                <th class="label-info">Cant Min Participantes</th>
                                <td><?php echo $this->datos[0] ['CantMiniAsis']; ?></td>
                            </tr>
                            <tr>
                                <th class="label-info">Descripción</th>
                                <td><?php echo $this->datos[0] ['Descripcion']; ?></td>
                            </tr>

                        </tbody>
                    </table>

                <?php else: ?>

                    <p><strong>No hay Evento!</strong></p>

                <?php endif; ?>                             

            </div>
        </div>

    </div>
</div>