<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Registro</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-sm-12">
                            <h3><?php echo $this->titulo ?></h3>
                        </div><br>
                        <div class="col-sm-12">
                            <a class="btn btn-sm btn-primary " href="<?php echo BASE_URL . 'agenda/buscar'; ?>" role="button">Volver</a>
                            <div class="modal fade" id="miventana1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidenn="true">&times;</button>
                                            <h4>Esta seguro que desea guardarlo</h4>
                                        </div>

                                        <div class="modal-footer discurso-enfatizado">
                                            <a class="btn btn-sm btn-success " data-dismiss="modal" href="#" role="button">No</a>
                                            <button class="btn btn-sm btn-success " type="button" onclick="document.form1.submit()"  >Sí</button>
                                        </div>
                                    </div>
                                </div>          
                            </div>
                        </div>
                        <br>
                        <div class="col-md-8  col-md-offset-2">
                            <?php //if (isset($this->datos) && count($this->datos)): ?>
                                <form name="form1" id="form1" action="<?php echo BASE_URL . 'agenda/modificar/' . $this->id; ?>" method="POST">
                                    <div class="col-md-12">

                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Id</div>
                                            <div class="col-md-8">1</div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Asistente</div>
                                            <div class="col-md-8">- - -</div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Comprador</div>
                                            <div class="col-md-8">- - -</div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Vendedor</div>
                                            <div class="col-md-8">- - -</div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Mesa</div>
                                            <div class="col-md-8">- - -</div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-4 label-custom">Estado</div>
                                            <div class="col-md-8">- - -</div>
                                        </div>

                                    </div>
                                </form>
                                <div class="col-md-12 text-center">
                                    <br>
                                    <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#miventana1">Confirmar</button>
                                </div>                <?php // else: ?>


                            <?php //endif; ?>                             

                        </div>

                    </div>
                </div>
            </div>        
        </div>
    </div>
</div>