<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Registro Empresas Participantes</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-sm-12">
                            <h3><?php echo $this->titulo ?></h3>
                        </div><hr/>
                        <div class="col-sm-12" >
                            <a class="btn btn-sm btn-success " href="<?php echo BASE_URL . 'empresa/nuevo'; ?>" role="button">Nuevo Registro</a>

                        </div>
                        <br>
                        <hr>
                        <?php if (isset($this->datos) && count($this->datos)): ?>
                            <div class="table-bordered col-sm-12 label-custom-back text-left">
                                <div class="col-sm-1"><label class="label-custom">Nit</label></div>
                                <div class="col-sm-4"><label class="label-custom">Nombre</label></div>
                                <div class="col-sm-2"><label class="label-custom">Participación</label></div>
                                <div class="col-sm-2"><label class="label-custom">Departamento</label></div>
                                <div class="col-sm-2"><label class="label-custom">Sector Ecónomico</label></div>
                                <div class="col-sm-1"><label class="label-custom">Acciones</label></div>
                            </div>
                            <?php for ($i = 0; $i < count($this->datos); $i++): ?>
                                <div class="table-bordered col-sm-12">
                                    <div class="col-sm-1"><?php echo $this->datos[$i] ['Nit']; ?></div>
                                    <div class="col-sm-4"><?php echo $this->datos[$i] ['Nombre']; ?></div>
                                    <div class="col-sm-2"><?php echo $this->datos[$i] ['TipoEmpresa']; ?></div>
                                    <div class="col-sm-2"><?php echo $this->datos[$i] ['Departamento']; ?></div>
                                    <div class="col-sm-2"><?php echo $this->datos[$i] ['SectorEconomico']; ?></div>
                                    <div class="col-sm-1">
                                        <a class=" btn btn-sm btn-warning " href="<?php echo BASE_URL . 'empresa/ver/' . $this->datos[$i] ['Nit']; ?>" role="button">Editar</a>
                                    </div>
                                </div>
                            <?php endfor; ?>
                        <?php else: ?>
                            <div class="col-sm-12">            
                                <p><strong>No hay Empresas!</strong></p> 
                            </div>
                        <?php endif; ?>                
                    </div>
                </div>

            </div>
        </div>
    </div>        

</div>


