<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Registro Empresas Participantes</h3>
                    </div>
                    <div class="panel-body">

                        <form class="" name="form1" id="form1" action="<?php echo BASE_URL . 'evento/insertar/' ?>" method="POST">

                            <div class="row">
                                <div class="col-md-6">
                                    <label class="">NIT de la empresa</label>
                                    <input class="" name="txtNIT" id="txtNIT" type="text" value="">
                                    <br/><br/>
                                    <label class="">Nombre de la empresa</label>
                                    <input class="" name="txtNombre" id="txtNombre" type="text" value="">
                                    <br/><br/><br/>
                                    <label class="">Tipo de empresa</label>
                                    <select class="" name="cmbTipoe" id="cmbTipo">
                                        <option value="0"> - - - seleccione - - - </option>
                                        <option value="1">Comprador</option>
                                        <option value="2">Vendedor</option>
                                    </select>
                                    <br/><br/>
                                    <label class="">Direccion empresa</label>
                                    <input class="" type='text' name="txtDireccion" id="txtDireccion" value="">                                
                                    <br/><br/>

                                    <label class="">Identificacion del propietario</label>
                                    <input class="" name="txtIdp" id="txtIdp" type='text' value="">
                                    <br/><br/><br/>

                                    <label class="">Nombres del propietario</label>
                                    <input name="txtNombrep" id="txtNombrep" type="text" class="" value="">
                                    <br/><br/>



                                </div>

                                <div class="col-md-6">
                                    <label class="">Celular</label>
                                    <input name="numCel" id="numCel" type="number" class="" value="">

                                    <br/><br/>

                                    <label class="">Telefono</label>
                                    <input name="numTel" id="numTel" type="number" class="" value="">

                                    <br/><br/>

                                    <label class="">Correo</label>
                                    <input name="txtEmail" id="txtEmail" type="email" class="" value="">

                                    <br/><br/>

                                    <label class="">Departamento</label>
                                    <select class=""><option> - - - seleccione - - -</option>
                                        <option value="1">Amazonas</option>
                                        <option value="2">Antioquia</option>
                                        <option value="3">Arauca</option>
                                        <option value="4">Atlantico</option>
                                        <option value="5">Bolivar</option>
                                        <option value="6">Boyacá</option>
                                        <option value="7">Caldas</option>
                                        <option value="8">Caquetá</option>
                                        <option value="9">Casanare</option>
                                        <option value="10">Cauca</option>
                                        <option value="11">Cesar</option>
                                        <option value="12">Chocó</option>
                                        <option value="13">Córdoba</option>
                                        <option value="14">Cundinamarca</option>
                                        <option value="15">Guainía</option>
                                        <option value="16">Guaviare</option>
                                        <option value="17">Huila</option>
                                        <option value="18">La Guajira</option>
                                        <option value="19">Magdalena</option>
                                        <option value="20">Meta</option>
                                        <option value="21">Nariño</option>
                                        <option value="22">Norte de Santander</option>
                                        <option value="23">Putumayo</option>
                                        <option value="24">Quindio</option>
                                        <option value="25">Risaralda</option>
                                        <option value="26">San Andres y Providencia</option>
                                        <option value="27">Santander</option>
                                        <option value="28">Sucre</option>
                                        <option value="29">Tolima</option>
                                        <option value="30">Valle del Cauca</option>
                                        <option value="31">Vaupés</option>
                                        <option value="32">Vichada</option>
                                        <option value="33">Bogotá D.C</option>
                                    </select>

                                    <br/><br/>

                                    <label class="">Municipio</label>
                                    <input name="txtMunicipio" id="txtMunicipio" type="text" class="" value="">

                                    <br/><br/>

                                    <label class="">Sector economico y/o comercial</label>
                                    <select class="">
                                        <option value="0"> - - - seleccione - - -</option>
                                        <option value="1">Agroindustria</option>
                                        <option value="2">Hotelería y Turismo</option>
                                        <option value="3">Comercio al Por Menor</option>
                                        <option value="4">Comercio al Por Mayor</option>
                                        <option value="5">Gastronomía</option>
                                        <option value="6">Construcción</option>
                                        <option value="7">Sector Financiero</option>
                                        <option value="8">Sector Gobierno</option>
                                        <option value="9">Industria</option>
                                        <option value="10">Minería Energía</option>
                                        <option value="11">Servicios</option>
                                        <option value="12">Sector Solidario (Cooperativas)</option>
                                        <option value="13">Farmacéuticos</option>
                                        <option value="14">Transporte Carga o Pasajeros</option>
                                        <option value="15">Otro</option>
                                    </select>

                                    <br/><br/><br/>

                                    <label class="">Padrino</label>
                                    <select class="">
                                        <option value="0"> - - - seleccione - - -</option>
                                        <option value="1">Padrino 1</option>
                                        <option value="2">Padrino 2</option>
                                        <option value="3">Padrino 3</option>
                                        <option value="4">Padrino 4</option>
                                    </select>

                                </div>
                            </div>
                        </form>

                        <hr class="btn-custom"/>

                        <form class="" id="form5" name="form5" action="#" method="POST">

                            <h4 class="panel-title">Asistentes</h4>
                            <hr class="btn-default" style="width: 90%"/>
                            <label class="">Asistente 1</label>
                            <input class="" name="encargado1" id="encargado1" type="text">

                            <button class="btn btn-success glyphicon glyphicon-plus">  otro encagado</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>        

</div>


