<style type="text/css">
    .vert .simply-scroll-clip {
        height: 400px;
    }
    #vende {
        height: 100%;
    }
    #compra{
        height: 100%;
    }
</style>
<div class="container col-md-12">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Empresas Participantes en Rueda de Negocios</h3>
                    </div>
                    <div class="panel-body">


                        <div class="table-bordered col-sm-6 text-center label-custom-back">
                            <div class="col-sm-12">
                                <label class="label-custom">Compradoras</label>
                            </div>

                        </div>
                        <div class="table-bordered col-sm-6 text-center label-custom-back">
                            <div class="col-sm-12">
                                <label class="label-custom">Vendedoras</label>
                            </div>

                        </div>                        
                        <script type="text/javascript">
                            (function($) {
                                $(function() {
                                    $("#scroller1").simplyScroll({
                                        orientation: 'vertical',
                                        customClass: 'vert',
                                        speed: 1,
                                    });
                                    $("#scroller2").simplyScroll({
                                        orientation: 'vertical',
                                        customClass: 'vert',
                                        speed: 1,
                                    });
                                });
                            })(jQuery);
                        </script>


                        <!-- Primera Columna -->
                        <div class="col-sm-6 table-bordered">
                            <ul id="scroller1">

                                <li id="compra" class="table-bordered">
                                    <?php for ($i = 0; $i < count($this->compra); $i++) { ?><div class="row table-bordered">
                                            <div class="col-sm-12">
                                                <label class="label-custom text-uppercase"><?php echo $this->compra[$i]['Nombre'] ?></label>
                                            </div>
                                            <div class="col-sm-12"><h6><strong><?php echo $this->compra[$i]['SectorEconomico'] ?></strong></h6></div>
                                            <div class="row">

                                                <div class="col-sm-12">
                                                    <?php for ($j = 0; $j < count($this->intencion[$this->compra[$i]['Nit']]); $j++) { ?>
                                                        <div class="col-sm-12 text-capitalize">- <?php echo $this->intencion[$this->compra[$i]['Nit']][$j]['Nombre'] ?></div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div><?php } ?> 
                                </li>
                                <li>
                                    <div class="col-sm-12">
                                        <hr>
                                    </div>
                                </li>


                            </ul>  
                        </div>
                        <!-- Segunda Columna -->
                        <div class="col-sm-6 table-bordered">
                            <ul id="scroller2">
                                <li id="vende" class="table-bordered">
                                    <?php for ($i = 0; $i < count($this->vende); $i++) { ?>
                                        <div class="row table-bordered">
                                            <div class="col-sm-12">
                                                <label class="label-custom text-uppercase"><?php echo $this->vende[$i]['Nombre'] ?></label>
                                            </div>
                                            <?php for ($j = 0; $j < count($this->productos[$this->vende[$i]['Nit']]); $j++) { ?>
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <div class="col-sm-12 text-lowercase"><?php echo $this->productos[$this->vende[$i]['Nit']][$j]['NomCat'] ?></div>
                                                    </div>
                                                    <div class="col-sm-6">
                                                        <div class="col-sm-12 text-lowercase"><?php echo $this->productos[$this->vende[$i]['Nit']][$j]['NomPro'] ?></div>
                                                    </div></div>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </li>
                                <li>
                                    <div class="col-sm-12">
                                        <hr>
                                    </div>
                                </li>
                            </ul>  
                        </div>
                        <br>&nbsp;
                        <div class="col-sm-12">
                            <div class="col-sm-4 text-right">
                                <label class="label-custom">Total Compradoras</label>
                            </div>
                            <div class="col-sm-2">
                                <input class="text-center" size="10" value="<?php echo count($this->compra) ?>">                        
                            </div>
                            <div class="col-sm-4 text-right">
                                <label class="label-custom">Total Vendedoras</label>
                            </div>
                            <div class="col-sm-2">
                                <input class="text-center" size="10" value="<?php echo count($this->vende) ?>">                     
                            </div>

                        </div>
                        <hr>
                        <br>
                    </div>
                </div>

            </div>
        </div>
    </div>        

</div>


