<style type="text/css">
    .vert .simply-scroll-clip {
        height: 400px;
    }
    .vert .simply-scroll-list li {
        height: 100px;
    }
</style>
<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Empresas Participantes Rueda de Negocios</h3>
                    </div>
                    <div class="panel-body">


                        <div class="table-bordered col-sm-6 text-center label-custom-back">
                            <div class="col-sm-12">
                                <label class="label-custom">Vendedoras</label>
                            </div>

                        </div>
                        <div class="table-bordered col-sm-6 text-center label-custom-back">
                            <div class="col-sm-12">
                                <label class="label-custom">Compradoras</label>
                            </div>

                        </div>                        
                        <script type="text/javascript">
                            (function($) {
                                $(function() {
                                    $("#scroller1").simplyScroll({
                                        orientation: 'vertical',
                                        customClass: 'vert',
                                        speed: 1,
                                    });
                                    $("#scroller2").simplyScroll({
                                        orientation: 'vertical',
                                        customClass: 'vert',
                                        speed: 1,
                                    });
                                });
                            })(jQuery);
                        </script>
                        <!-- Primera Columna -->
                        <div class="col-sm-6 table-bordered">
                            <ul id="scroller2">
                                <li class="table-bordered">
                                    <div>
                                        <div class="col-sm-12">
                                            <label class="label-custom">Empresa Vendedora 1</label>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Categoria 1</div>
                                            <div class="col-sm-12">Categoria 2</div>
                                            <div class="col-sm-12">Categoria 3</div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Producto 1</div>
                                            <div class="col-sm-12">Producto 2</div>
                                            <div class="col-sm-12">Producto 3</div>
                                        </div>
                                    </div>
                                </li>
                                <li class="table-bordered">
                                    <div>
                                        <div class="col-sm-12">
                                            <label class="label-custom">Empresa Vendedora 2</label>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Categoria 1</div>
                                            <div class="col-sm-12">Categoria 2</div>
                                            <div class="col-sm-12">Categoria 3</div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Producto 1</div>
                                            <div class="col-sm-12">Producto 2</div>
                                            <div class="col-sm-12">Producto 3</div>
                                        </div>
                                    </div>
                                </li>
                                <li class="table-bordered">
                                    <div>
                                        <div class="col-sm-12">
                                            <label class="label-custom">Empresa Vendedora 3</label>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Categoria 1</div>
                                            <div class="col-sm-12">Categoria 2</div>
                                            <div class="col-sm-12">Categoria 3</div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Producto 1</div>
                                            <div class="col-sm-12">Producto 2</div>
                                            <div class="col-sm-12">Producto 3</div>
                                        </div>
                                    </div>
                                </li>
                                <li class="table-bordered">
                                    <div>
                                        <div class="col-sm-12">
                                            <label class="label-custom">Empresa Vendedora 4</label>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Categoria 1</div>
                                            <div class="col-sm-12">Categoria 2</div>
                                            <div class="col-sm-12">Categoria 3</div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Producto 1</div>
                                            <div class="col-sm-12">Producto 2</div>
                                            <div class="col-sm-12">Producto 3</div>
                                        </div>
                                    </div>
                                </li>                                
                                <li class="table-bordered">
                                    <div>
                                        <div class="col-sm-12">
                                            <label class="label-custom">Empresa Vendedora 5</label>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Categoria 1</div>
                                            <div class="col-sm-12">Categoria 2</div>
                                            <div class="col-sm-12">Categoria 3</div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="col-sm-12">Producto 1</div>
                                            <div class="col-sm-12">Producto 2</div>
                                            <div class="col-sm-12">Producto 3</div>
                                        </div>
                                    </div>
                                </li>
                            </ul>  
                        </div>

                        <!-- Segunda Columna -->
                        <div class="col-sm-6 table-bordered">
                            <ul id="scroller1">
                                <li class="table-bordered">
                                    <div>
                                        <div class="col-sm-12">
                                            <label class="label-custom">Empresa Compradora 1</label>
                                        </div>
                                        <div class="col-sm-3">
                                            <div class="col-sm-12">Requiere</div>
                                        </div>
                                        <div class="col-sm-9">
                                            <div class="col-sm-12">Categoria 1</div>
                                            <div class="col-sm-12">Categoria 2</div>
                                            <div class="col-sm-12">Categoria 3</div>
                                        </div>
                                    </div>
                                </li>
                                <li class="table-bordered">
                                    <div>
                                        <div class="col-sm-12">
                                            <label class="label-custom">Empresa Compradora 2</label>
                                        </div>
                                        <div class="col-sm-3">
                                            <div class="col-sm-12">Requiere</div>
                                        </div>
                                        <div class="col-sm-9">
                                            <div class="col-sm-12">Categoria 1</div>
                                            <div class="col-sm-12">Categoria 2</div>
                                            <div class="col-sm-12">Categoria 3</div>
                                        </div>
                                    </div>
                                </li>
                                <li class="table-bordered">
                                    <div>
                                        <div class="col-sm-12">
                                            <label class="label-custom">Empresa Compradora 4</label>
                                        </div>
                                        <div class="col-sm-3">
                                            <div class="col-sm-12">Requiere</div>
                                        </div>
                                        <div class="col-sm-9">
                                            <div class="col-sm-12">Categoria 1</div>
                                            <div class="col-sm-12">Categoria 2</div>
                                            <div class="col-sm-12">Categoria 3</div>
                                        </div>
                                    </div>
                                </li>
                                <li class="table-bordered">
                                    <div>
                                        <div class="col-sm-12">
                                            <label class="label-custom">Empresa Compradora 5</label>
                                        </div>
                                        <div class="col-sm-3">
                                            <div class="col-sm-12">Requiere</div>
                                        </div>
                                        <div class="col-sm-9">
                                            <div class="col-sm-12">Categoria 1</div>
                                            <div class="col-sm-12">Categoria 2</div>
                                            <div class="col-sm-12">Categoria 3</div>
                                        </div>
                                    </div>
                                </li>                                

                            </ul>  
                        </div>
                        <br>&nbsp;
                        <div class="col-sm-12">
                            <div class="col-sm-4 text-right">
                                <label class="label-custom">Total Vendedoras</label>
                            </div>
                            <div class="col-sm-2">
                                <input class="text-center" size="10" value="1">                     
                            </div>
                            <div class="col-sm-4 text-right">
                                <label class="label-custom">Total Compradoras</label>
                            </div>
                            <div class="col-sm-2">
                                <input class="text-center" size="10" value="1">                        
                            </div>
                        </div>
                        <hr>
                        <br>
                    </div>
                </div>

            </div>
        </div>
    </div>        

</div>
</div>
