<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default sombra">
                <div class="panel-body">
                    <div class="bs-example" data-example-id="carousel-with-captions">
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="1"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="2"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="3"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="4"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="5"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="6"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>fo11.png" alt="Unidad 1">
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>fo10.png" alt="Unidad 2">
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>fo14.png" alt="Unidad 3">
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>fo2.png" alt="Unidad 4">
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>fo3.png" alt="Unidad 5">
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>fo6.png" alt="Unidad 5">
                                </div>
                             <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>fo9.png" alt="Unidad 5">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div><!-- /example -->
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default sombra">
                <div class="panel-heading">Bandeja de Entrada</div>
                <div class="panel-body">
                    Contenido de la bandeja de entrada
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default sombra">
                <div class="panel-body">
                    <p class="text-justify">SGTH (Sistema de Gestión de Talento Humano) ofrece al coordinador de talento humano el manejo de la información de una manera 
                        eficiente y óptima en cuanto el registro de personas y su relación con el centro de formación.</p> 
                    <p class="text-justify">Esta aplicación la pueden acceder 
                        todos los usuarios según su vinculación y rol que desempeña en el centro. 
                        Además, fortalece la toma de decisiones en la administración de personal. 
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

