<div class="container">
    <a href="#" id="example" class="btn large primary" >click for popover</a>
    
    <a class="btn-link" href="#" data-toggle="tooltip" data-placement="bottom" title="Tooltip on left">Tooltip on left</a>
    
    
    <a id="7713344" class="hoverToolTip" data-id="7713344" data-page="busca/">Data1</a>
    <a id="123434" class="hoverToolTip" data-id="1234567" data-page="busca/">Data2</a>
    
    <div class="popover-all">Example</div>
</div>