<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Parametros Generales</h3>
                    </div>
                    <div class="panel-body">
                        <form id="form1" name="form1" method="post" action="<?php echo BASE_URL.'paramentros/guardar'?>">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="row">
                                <div  class="col-md-3 text-right label-custom">Nro Mesas</div>
                                <div  class="col-md-3 "><input  class="text-center" type="text" size="10px" value="123"></div>
                                <div  class="col-md-3 text-right label-custom">Minutos por Cita</div>
                                <div  class="col-md-3 "><input class="text-center" type="text" size="10px" value="123""></div>
                            </div>
                            <br>
                            <div class="row">
                                <div  class="col-md-3 text-right label-custom">Hora Inicio Mañana</div>
                                <div  class="col-md-3 "><input class="text-center" type="text" size="10px" value="123""></div>
                                <div  class="col-md-3 text-right label-custom">Hora Inicio Tarde</div>
                                <div  class="col-md-3 "><input class="text-center" type="text" size="10px" value="123""></div>
                            </div>                            
                            <div class="row">
                                <div  class="col-md-3 text-right label-custom">Citas Asignar Mañana</div>
                                <div  class="col-md-3 "><input class="text-center" type="text" size="10px" value="123""></div>
                                <div  class="col-md-3 text-right label-custom">Citas Asignar Tarde</div>
                                <div  class="col-md-3 "><input class="text-center" type="text" size="10px" value="123""></div>
                            </div>
                            <div class="row">
                                <div  class="col-md-6 text-right label-custom">Nro de Citas por linea en Reporte</div>
                                <div  class="col-md-6 ">
                                    <select class="">
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>6</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row text-center">
                                <button class="btn-custom" type="submit">Guardar</button>
                            </div>
                        </div>



                        </form>
                    </div>
                </div>
            </div>
        </div>        
    </div>
</div>