<div class="container">
    <div class="contenedor">
        <div class="row">
            <div class="col-sm-10 col-lg-offset-1">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <h3 class="panel-title">Parametros Generales</h3>
                    </div>
                    <div class="panel-body">
                        <form id="form1" name="form1" method="post" action="<?php echo BASE_URL . 'parametros/guardar' ?>">
                            <div class="col-md-10 col-md-offset-1">
                                <div class="row">
                                    <div  class="col-md-3 text-right label-custom">Nro Mesas</div>
                                    <div  class="col-md-3 "><input name="txtMesas"  class="text-center" type="text" size="10px" value="<?php echo $this->datos[0] ['Mesas']; ?>"></div>
                                    <div  class="col-md-3 text-right label-custom">Minutos por Cita</div>
                                    <div  class="col-md-3 "><input name="txtMinutos" class="text-center" type="text" size="10px" value="<?php echo $this->datos[0] ['Minutos']; ?>"></div>
                                </div>
                                <br>
                                <div class="row">
                                    <div  class="col-md-3 text-right label-custom">Hora Inicio Mañana</div>
                                    <div  class="col-md-3 ">
                                        <input name="txtInicioMH" class="text-center" type="text" size="1" value="<?php echo $this->datos[0] ['InicioMH']; ?>">
                                        <strong>:</strong> <input name="txtInicioMM" class="text-center" type="text" size="1" value="<?php echo $this->datos[0] ['InicioMM']; ?>">
                                    </div>
                                    <div  class="col-md-3 text-right label-custom">Hora Inicio Tarde</div>
                                    <div  class="col-md-3 "><input name="txtInicioTH" class="text-center" type="text" size="1" value="<?php echo $this->datos[0] ['InicioTH']; ?>">
                                        <strong>:</strong> <input name="txtInicioTM" class="text-center" type="text" size="1" value="<?php echo $this->datos[0] ['InicioTM']; ?>">
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div  class="col-md-3 text-right label-custom">Citas Asignar Mañana</div>
                                    <div  class="col-md-3 "><input name="txtCitasM" class="text-center" type="text" size="10px" value="<?php echo $this->datos[0] ['CitasM']; ?>"></div>
                                    <div  class="col-md-3 text-right label-custom">Citas Asignar Tarde</div>
                                    <div  class="col-md-3 "><input name="txtCitasT" class="text-center" type="text" size="10px" value="<?php echo $this->datos[0] ['CitasT']; ?>"></div>
                                </div>
                                <br>
                                <div class="row">
                                    <div  class="col-md-6 text-right label-custom">Nro de Citas por linea en Reporte</div>
                                    <div  class="col-md-6 ">
                                        <select name="cmbCols" class="" >
                                            <?php
                                            $col=$this->datos[0] ['Cols'];
                                            for ($numcol = 2; $numcol < 6; $numcol++) {
                                                if ($numcol == $col) {
                                                    echo "<option value=".$numcol." selected> ".$numcol." </option>";
                                                } else {
                                                    echo "<option value=".$numcol."> ".$numcol." </option>";
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <br>
                                <div class="row text-center">
                                    <button class="btn-custom" type="submit">Guardar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>        
    </div>
</div>