<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default sombra">
                <div class="panel-body">
                    <div class="bs-example" data-example-id="carousel-with-captions">
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="1"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="2"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="3"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="4"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="5"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="6"></li>
                                <li data-target="#carousel-example-captions" data-slide-to="7"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>v0.jpg">
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>v1.jpg">
                                    <div class="carousel-caption">
                                        <p>1. Diríjase al lugar destinado para la votación</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>v2.jpg">
                                    <div class="carousel-caption">
                                        <p>2. Presente el carné que lo identifica como Aprendiz al jurado de votación</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>v3.jpg">
                                    <div class="carousel-caption">
                                        <p>3. El jurado verifica en el sistema su identidad y lo habilita para votar</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>v4.jpg">
                                    <div class="carousel-caption">
                                        <p>4. Diríjase a la mesa de su preferencia y verifique la disponibilidad del equipo a utilizar</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>v5.jpg">
                                    <div class="carousel-caption">
                                        <p>5. Digite su número de identificación y espere que el tarjetón se cargue completamente</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>v6.jpg">
                                    <div class="carousel-caption">
                                        <p>6. De click sobre la foto o número del candidato de su preferencia y confirme su elección</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>v7.jpg">
                                    <div class="carousel-caption">
                                        <p>7. Verifique que el sistema registró su voto y que vuelve a la página de inicio</p>
                                    </div>
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div><!-- /example -->
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange text-center">Como Votar...</h4></div>
                <div class="panel-body">
                    <ol>
                        <li class="text-left">Diríjase al lugar destinado para la votación</li>
                        <li class="text-left">Presente el carné que lo identifica como Aprendiz al jurado de votación</li>
                        <li class="text-left">El jurado verifica en el sistema su identidad y lo habilita para votar</li>
                        <li class="text-left">Diríjase a la mesa de su preferencia y verifique la disponibilidad del equipo a utilizar</li>
                        <li class="text-left">Digite su número de identificación y espere que el tarjetón se cargue completamente</li>
                        <li class="text-left">De click sobre la foto o número del candidato de su preferencia y confirme su elección</li>
                        <li class="text-left">Verifique que el sistema registró su voto y que vuelve a la página de inicio</li>
                        <li class="text-left">Disponga la mesa para otro aprendiz</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-warning sombra">
                <div class="panel-heading"><h4 class="label-orange text-center">Normatividad</h4></div>
                <div class="panel-body">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:0 0 0 0 0 0 0 0 0 0;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:Verdana;
	panose-1:2 11 6 4 3 5 4 4 2 4;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:8.0pt;
	margin-left:0cm;
	line-height:107%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
p
	{margin-right:0cm;
	margin-left:0cm;
	font-size:12.0pt;
	font-family:"Times New Roman","serif";}
p.centrado, li.centrado, div.centrado
	{mso-style-name:centrado;
	margin-right:0cm;
	margin-left:0cm;
	font-size:12.0pt;
	font-family:"Times New Roman","serif";}
span.baj
	{mso-style-name:b_aj;}
span.apple-converted-space
	{mso-style-name:apple-converted-space;}
span.iaj
	{mso-style-name:i_aj;}
.MsoChpDefault
	{font-family:"Calibri","sans-serif";}
.MsoPapDefault
	{margin-bottom:8.0pt;
	line-height:107%;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 3.0cm 70.85pt 3.0cm;}
div.WordSection1
	{page:WordSection1;}
-->
</style>    

<div class=WordSection1>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
style='font-size:8.5pt;font-family:"Arial","sans-serif";color:#FFA200'>ACUERDO
2 DE 2014</span></b></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>(Febrero
20)</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Diario
Oficial No. 49.071 de 21 de febrero de 2014</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#FFA200'>SERVICIO
NACIONAL DE APRENDIZAJE</span></b></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Por el
cual se modifica el Capítulo XI del Acuerdo número 007&nbsp;de 2012.</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#FFA200'>EL
CONSEJO DIRECTIVO NACIONAL DEL SERVICIO NACIONAL DE APRENDIZAJE (SENA),</span></b></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>en
ejercicio de las facultades legales y en especial las que le confiere el
numeral 8 del artículo&nbsp;3o del Decreto número 249 del 28 de enero de
2004, y</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#FFA200'>CONSIDERANDO:</span></b></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Que la
Constitución Política de Colombia señala en su artículo&nbsp;67&nbsp;que:&nbsp;<i>“La educación es un
derecho de la persona y un servicio público que tiene como función social: con
ella se busca el acceso al conocimiento, a la ciencia, a la técnica, y a los
demás bienes y valores de la cultura. La educación formará al colombiano en el
respeto de los derechos humanos, a la paz y a la democracia, en la práctica del
trabajo y en la recreación, para el mejoramiento cultura, científico, tecnológico
y para la protección del ambiente”;</i></span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Que la
Ley&nbsp;119&nbsp;de 1994 establece que:&nbsp;<i>“El
Sena, está encargado de cumplir la función que corresponde al Estado de
invertir en el desarrollo social y técnico de los trabajadores colombianos;
ofreciendo y ejecutando la formación profesional integral para la incorporación
y el desarrollo de las personas en actividades productivas que contribuyan al
desarrollo social, económico y tecnológico del país”;</i></span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Que el
artículo&nbsp;4o de la Ley 119 de 1994, establece como
función del Sena, entre otras:&nbsp;<i>“1. Impulsar la promoción social del
trabajador a través de su formación profesional integral, para hacer de él un
ciudadano útil y responsable, poseedor de valores morales éticos, culturales y
ecológicos”;</i></span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Que el
Aprendiz es el centro de la formación profesional integral y es deber del Sena
propender por los más altos niveles de excelencia en cumplimiento de la misión
y objetivos que le han sido trazados;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Que para
la convivencia armoniosa de toda comunidad educativa se requiere el
establecimiento y cumplimiento de normas mínimas de comportamiento y
convivencia, concordadas con las disposiciones relativas al proceso de
aprendizaje;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Que de
conformidad con lo dispuesto al numeral 8 del artículo&nbsp;3o del Decreto número 249 de 2004 es función
del Consejo Directivo Nacional del Sena:&nbsp;<i>“8. Regular los sistemas o
normas para la selección, orientación, promoción y formación profesional
integral de los trabajadores alumnos y&nbsp;</i></span><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>expedir
el reglamento al que deben someterse el cual comprenderá sus derechos, deberes,
reglas de permanencia y el régimen sancionatorio</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>”. (</span></i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Resaltado
fuera de texto);</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Que en
cumplimiento de esta función el Consejo Directivo adoptó el Reglamento del
Aprendiz mediante Acuerdo número&nbsp;7&nbsp;de 2012;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Que la
Dirección de Formación Profesional realizó una revisión del contexto normativo
del reglamento del aprendiz, y con el fin de brindar mecanismos para que los
aprendices tengan espacios de participación y representación, como componente
fundamental de la democracia institucional, por medio de la existencia de
elecciones libres, legales, legítimas y periódicas, es necesario modificar el
Capítulo XI de la representación de los aprendices;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>En
virtud de lo anterior,</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#FFA200'>ACUERDA:</span></b></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><a name=1><b><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:black'>ARTÍCULO
1o.</span></b></a><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>&nbsp;Modificar el Capítulo XI del Acuerdo número&nbsp;0007&nbsp;de 2012, el cual queda así:</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>CAPÍTULO
XI</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#FFA200'>De la
representación de los aprendices</span></b></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;37. Representación de aprendices.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>La
representación es la figura que surge del ejercicio democrático realizado en
todos los Centros de Formación y en el que participan de manera libre y
espontánea los aprendices Sena para elegir un Aprendiz que los represente ante
la Dirección General del Sena, la Regional y el Centro de Formación. Quien sea
elegido Representante de Aprendiz Sena tiene un compromiso con los aprendices,
con la Institución y con la comunidad educativa.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;38. Representante de Centro.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Podrán
ser representantes los Aprendices Sena que se encuentren matriculados y
cursando su etapa lectiva en programas técnicos y tecnológicos ofrecidos en las
sedes y sub sedes de los Centros de Formación.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;39. Número de Representantes y periodo.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Cada
Centro de Formación Sena tendrá un Representante de Aprendiz Sena por jornada
así: virtual, diurna, mixta, nocturna, 24 horas y fin de semana.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Parágrafo.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Será
suplente del Representante de Aprendiz Sena, el candidato por jornada que haya
obtenido la segunda mayor votación.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;40. Requisitos y condiciones para ser elegido
Representante de Aprendiz Sena.&nbsp;</span></i></b><i><span style='font-size:
9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Para ser elegido
Representante de Aprendiz Sena del Centro de Formación se requiere:</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>a) Estar
vinculado en un programa de formación técnica o tecnológica en el Sena;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>b)
Presentar una propuesta programática la cual implementará en su periodo de
representación y deberá proyectarse bajo los valores del aprendiz Sena,
teniendo en cuenta los siguientes contenidos:</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>-- Una
estrategia que permita garantizar los derechos de los aprendices Sena en sus
Centros de Formación.</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>-- Una
idea de proyecto de fortalecimiento en un espacio de su comunidad, para
desarrollar bajo los parámetros del programa Sena en Comunidad, y el cual se
desarrollará de acuerdo a la viabilidad del mismo;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>c) Estar
vinculado al voluntariado Sena;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>d) Ser
parte activa del Sistema Nacional de Liderazgo;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>e) No
haber cursado más de tres trimestres de su programa de formación. (9 meses);</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>f) No
haber sido Representante de los aprendices en ningún Centro de Formación Sena;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>g)
Mostrar aptitudes de responsabilidad para asumir como Representante, sin
descuidar las obligaciones del proceso de aprendizaje;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>h)
Formular propuestas de trabajo viables en beneficio del Centro de Formación y
de la comunidad educativa, utilizando las tecnologías de la información y los
canales institucionales del Sistema Nacional de Liderazgo;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>i) No
presentar ni haber presentado plan de mejoramiento, condicionamiento de matrícula,
ni llamados de atención escritos;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>j) No
presentar antecedentes disciplinarios de la Policía;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>k)
Obtener la mayoría de votos en el ejercicio electoral realizado en el Centro de
Formación.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Para los
Centros de Formación que tengan subsedes se elegirá un suplente que coordinará
acciones con el Representante de Aprendiz Sena de su jornada correspondiente.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>La
elección del Representante de Aprendiz Sena será desde el momento de la fecha
en que se elige y hasta el segundo lunes de marzo de cada año, momento en el
cual se realizará un nuevo proceso de elección en el Centro de Formación.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;41. Responsabilidades del Representante de
Aprendiz Sena.&nbsp;</span></i></b><i><span style='font-size:9.0pt;font-family:
"Arial","sans-serif";color:#7C7B7B'>Son responsabilidades del Representante de
Aprendiz Sena, las siguientes:</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>a)
Implementar su plan de acción con base en la propuesta programática;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>b)
Asistir a reuniones quincenales con el representante suplente y los voceros de
ficha para tratar temas específicos del área de formación, y de interés general
para los aprendices;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>c) Una
vez al mes deberá reunirse con los voceros de sus fichas en compañía del
Subdirector y el líder de bienestar del centro de formación, para revisar
avances y desarrollo del plan de acción acorde a la propuesta programática
presentada;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>d)
Actuar como canal de comunicación e interlocutor entre los estamentos de la
comunidad educativa y los aprendices con el fin de velar por el buen
funcionamiento del Centro de Formación;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>e)
Comunicar e incentivar la participación de los aprendices y la comunidad
educativa en: eventos culturales, curriculares, deportivos, artísticos,
tecnológicos, investigativos, de integración, Sistema Nacional de Liderazgo,
Sena en la Comunidad y Sena Voluntariado por Colombia;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>f) Promover
en coordinación con el representante suplente y los voceros del programa el
cumplimiento del Reglamento del Aprendiz Sena, apoyándose en el Grupo de
Fomento del Bienestar y Liderazgo del Aprendiz, o quien haga sus veces, líderes
Comunicadores, y los canales de comunicación internos; previa concertación con
el Subdirector y el Líder de Bienestar de su Centro de Formación;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>g)
Participar en la formulación del plan anual de Fomento del Bienestar y
Liderazgo del Aprendiz de su Centro de Formación;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>h) Integrar
y participar en el Comité de Cafetería si su Centro de Formación cuenta con el
mismo;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>i)
Promover, en coordinación con los voceros de programa y el representante
suplente, el cumplimiento de los derechos y deberes del Aprendiz Sena, para lo
cual podrá utilizar los medios de comunicación institucional previa
concertación con el Subdirector de Centro;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>j)
Participar como integrante del Comité de Evaluación y seguimiento de su Centro
de Formación;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>k)
Incentivar el cuidado y mantenimiento de los ambientes de aprendizaje y la
infraestructura física del Centro, dispuesta para el proceso de aprendizaje;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>l)
Representar a los aprendices de su Centro de Formación en reuniones, eventos y
actividades que propendan por el fomento del bienestar y liderazgo del
aprendiz;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>m)
Promover el fortalecimiento de las relaciones de convivencia en la comunidad
educativa, a través del diálogo, el buen trato, el respeto y la conciliación;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>n)
Participar en la preparación y ejecución de las actividades de inducción
pertenecientes al Grupo de Fomento del Bienestar y Liderazgo del Aprendiz o
quien haga sus veces, que programe el Centro de Formación, para los nuevos
aprendices.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;42.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>En caso
de requerir representatividad en eventos simultáneos que requieran la presencia
del Representante de Aprendiz Sena, se designará el suplente para que asista.
Para tal caso, se redactará un acta de mutuo acuerdo firmada por el Subdirector
del Centro y Líder del Grupo de Bienestar al Aprendiz o quien haga sus veces.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;43. Procedimiento para elegir Representante de
Aprendiz Sena</span></i></b><i><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>:</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>a)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Dependencia
responsable</span></i></b><i><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>: El grupo de Fomento del Bienestar y Liderazgo del Aprendiz de
la Dirección General o quien haga sus veces, elaborará el cronograma y abrirá
la convocatoria respectiva, mediante acto administrativo emitido por la
Dirección de Formación Profesional, a través del cual se convoca la elección
del Representante de Aprendiz Sena por jornadas en Centro de Formación;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>b)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Inscripción
de candidatos:&nbsp;</span></i></b><i><span style='font-size:9.0pt;font-family:
"Arial","sans-serif";color:#7C7B7B'>Los aprendices interesados en postularse a
la elección de Representante, pueden inscribirse en la convocatoria de
elección, en forma individual, inscribiéndose a través de los canales de
comunicación previstos y presentando la propuesta programática de trabajo para
el periodo anual de representación;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>c)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Verificación
de cumplimiento de requisitos</span></i></b><i><span style='font-size:9.0pt;
font-family:"Arial","sans-serif";color:#7C7B7B'>. El Grupo de Fomento del
Bienestar y Liderazgo del Aprendiz del Centro de Formación, o quien haga sus
veces, con apoyo de la Dirección General verificará el cumplimiento de los
requisitos de los aprendices inscritos durante la semana posterior a la
inscripción de la candidatura;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>d)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Divulgación
de los resultados.&nbsp;</span></i></b><i><span style='font-size:9.0pt;
font-family:"Arial","sans-serif";color:#7C7B7B'>El área de Fomento del
Bienestar y Liderazgo del Aprendiz en cada Centro de Formación o quien haga sus
veces, publicará los resultados de la verificación de los requisitos de los
candidatos inscritos;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>e)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Participación</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>. Para
el proceso de elección del Representante de Aprendiz Sena deberá participar
mínimo el 50% de los aprendices de formación titulada del Centro de Formación;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>f)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Votación.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>La
votación se realizará el segundo lunes de marzo de cada año, así: Jornada
diurna y 24 horas de 5:00 a. m. a 10 a. m.; jornada mixta y nocturna de 2 p. m.
a 7 p. m. Para la jornada fin de semana las votaciones se realizarán el domingo
anterior a la fecha de elecciones indicada, de 11 a. m. a 2 p. m. Las
votaciones se harán en urnas selladas o mediante el uso de herramientas
digitales con su correspondiente auditoría. Serán parte del grupo auditor un
delegado del Grupo de Fomento del Bienestar y Liderazgo del Aprendiz del Centro
de Formación, un aprendiz Sena y un delegado de cada candidatura siempre y
cuando no esté postulado al cargo de Representante del Centro;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>g)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Escrutinio</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>. El
Grupo de Fomento del Bienestar y Liderazgo del Aprendiz de cada Centro de
Formación o quien haga sus veces, hará parte de la comisión escrutadora siendo
garante y verificador del proceso. El escrutinio se realizará el día de cierre
de la votación. Se levantará acta debidamente suscrita por los integrantes de
la comisión escrutadora. La Comisión estará conformada por un vocero de
programa de formación, un Aprendiz elegido al azar, un Instructor, un
Coordinador Académico y un representante del área de Bienestar a los
Aprendices;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>h)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Elección.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Se
declararán ganadores a quienes obtengan la mayoría simple de votos. En caso de
existir empate, la Comisión Escrutadora definirá el ganador por sorteo en
presencia de los integrantes de las mismas. Se expedirá acta según formato
establecido y firmada por el Representante de Aprendiz Sena;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>i)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Publicación
del resultado electoral.&nbsp;</span></i></b><i><span style='font-size:9.0pt;
font-family:"Arial","sans-serif";color:#7C7B7B'>El resultado de la elección se
informará oficialmente por escrito a los candidatos, recordándoles los
compromisos asumidos y las responsabilidades que esta designación conlleva. De
igual forma, se publicará el resultado en las carteleras del Centro de
Formación, informando a la Comunidad Educativa el resultado de la votación;</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>j)&nbsp;</span></i><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Designación.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Se
realizará el acto protocolario el viernes siguiente a la elección, con la
expedición de la Resolución firmada por el Subdirector del Centro y ante la
Comunidad Educativa del Centro de Formación.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Parágrafo
1o.&nbsp;</span></i></b><i><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>Si en el escrutinio el voto en blanco supera el 50% más 1 de los
votos válidos, debe realizarse una nueva elección, la cual será convocada al
siguiente lunes de la fecha establecida (tercer lunes de marzo). Los candidatos
inscritos podrán mantener su postulación o retirarse, siempre y cuando cumplan
con los requisitos preestablecidos.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Parágrafo
2o.&nbsp;</span></i></b><i><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>Cuando el Centro de Formación presente condiciones atípicas que
impidan la elección del Representante de Aprendiz Sena en la fecha estipulada,
las elecciones deberán postergarse hasta que el Centro de Formación supere las
condiciones atípicas. Se deberá tener en cuenta un cronograma de por lo menos
tres (3) semanas para realizar el proceso electoral.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Parágrafo
3o.&nbsp;</span></i></b><i><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>En caso de que la Jornada del Centro de Formación no presente
candidatos inscritos para la elección del Representante de Aprendiz Sena, este
será escogido en reunión de voceros de la jornada correspondiente quienes
postularán tres candidatos, entre ellos se hará una votación cerrada con la
participación del Subdirector de Centro y el Líder de Fomento del Bienestar y
Liderazgo del Aprendiz del Centro. Se deberá llevar estricto registro por medio
de acta del desarrollo de la reunión.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Los
candidatos deberán cumplir las mismas condiciones estipuladas en el artículo&nbsp;38&nbsp;y&nbsp;40&nbsp;para ser Representante de Aprendiz
Sena.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;44. Revocatoria de la designación del
Representante de Aprendiz Sena.&nbsp;</span></i></b><i><span style='font-size:
9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>El Representante de
Aprendiz Sena puede ser removido de su representación perdiendo su investidura
y representatividad ante la comunidad educativa del Centro de Formación, por
las siguientes causales:</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>a)
Incumplimiento de sus responsabilidades como Representante de Aprendiz Sena;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>b) Bajo
rendimiento académico que amerite mayor dedicación a su formación;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>c)
Sanciones recibidas por aspectos académicos o disciplinarios dictaminado por el
comité de evaluación y seguimiento de conformidad con lo señalado en el
procedimiento para la aplicación de sanciones del reglamento del aprendiz;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>d)
Solicitud sustentada de la comunidad educativa;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>e)
Terminación anticipada de su proceso de formación en el Sena;</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>f)
Inicio de etapa productiva.</span></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Parágrafo
1o.&nbsp;</span></i></b><i><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>Para la revocatoria de la designación como Representante de
Aprendiz Sena el comité de evaluación y seguimiento se reunirá con el
Representante del Aprendiz Sena, el coordinador académico y el Subdirector del Centro,
analizarán la situación y tomarán las determinaciones que correspondan.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Parágrafo
2o.&nbsp;</span></i></b><i><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>Cuando opere la revocatoria para uno de los representantes
asumirá el cargo el Suplente.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Parágrafo
3o.&nbsp;</span></i></b><i><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>El acto administrativo de revocatoria de la Representación de
Aprendiz Sena no es susceptible de recursos en razón a que son actos
académicos.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;45.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>&lt;sic&gt;
En caso de que el Representante de Aprendiz Sena y el suplente salgan al mismo
tiempo a etapa productiva o por alguna otra circunstancia se dé la vacancia en
la representación, asumirá quien haya obtenido el tercer lugar en la elección y
así sucesivamente en orden descendente. El escogido deberá continuar gestionando
la propuesta programática del Representante elegido inicialmente por votación y
cumplir con las funciones señaladas en el artículo&nbsp;41&nbsp;del reglamento.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;46. &lt;sic&gt; Periodos de Representación.&nbsp;</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Los
períodos son de carácter institucional y no personal. Por consiguiente, en caso
de producirse la vacancia en la Representación del Aprendiz Sena, por cualquier
causa, el nuevo Representante será el suplente durante el tiempo faltante para
concluir el período o el tiempo que dure la ausencia del Representante.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#008400'>Artículo&nbsp;47. &lt;sic&gt; Presentación y difusión de
propuestas de trabajo ante la Comunidad Educativa</span></i></b><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>. El
Centro de Formación, a través del subdirector y con apoyo del Grupo de Fomento
del Bienestar y Liderazgo del Aprendiz del Centro o quien haga sus veces,
organizará sesiones para que los candidatos inscritos presenten su propuesta de
trabajo ante la comunidad educativa, convocando a todos los aprendices del
Centro de Formación.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Se
garantizará la divulgación de las propuestas de los candidatos en igualdad de
condiciones, durante quince días calendario previos a las elecciones mediante
los siguientes mecanismos:</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>1.
Medios impresos, usando únicamente las carteleras informativas con las que
cuente en centro de formación.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>2.
Medios electrónicos, como correo electrónico y las pantallas informativas de
los centros.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>3. Un
foro de participación al que se invite a toda la comunidad de aprendices y en
donde los aspirantes a representantes debatan sus propuestas en público.</span></i></p>

<p class=MsoNormal style='text-align:justify;line-height:normal'><i><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>4. Una
videoconferencia establecida previamente por el centro de formación.</span></i></p>


<p class=MsoNormal style='text-align:justify;line-height:normal'><a name=2><b><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:black'>ARTÍCULO
2o.</span></b></a><span style='font-size:9.0pt;font-family:"Arial","sans-serif";
color:#7C7B7B'>&nbsp;El presente acuerdo rige a partir de la fecha de su
publicación en el&nbsp;<i>Diario Oficial&nbsp;</i>y modifica el Capítulo XI del
Acuerdo número&nbsp;0007&nbsp;de 2012.</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Publíquese
y cúmplase.</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Dada en
Bogotá, D. C., a 20 de febrero de 2014.</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>El
Presidente del Consejo,</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#FFA200'>RAFAEL
PARDO RUEDA,</span></b></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>Ministro
del Trabajo.</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#7C7B7B'>La
Secretaria del Consejo,</span></p>

<p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
style='font-size:9.0pt;font-family:"Arial","sans-serif";color:#FFA200'>INGRID
CAROLINA SILVA RODRÍGUEZ.</span></b></p>

<p class=MsoNormal>&nbsp;</p>

</div>
                  
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>
