<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 text-center">
            <div class="panel panel-default sombra">
                <div class="panel-heading"><h4 class="label-orange">Votantes por titulación</h4></div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="datatable" class="table-bordered table-condensed table-striped table-hover col-md-12">
                            <thead>
                                <tr class="warning">
                                    <th>Ficha</th>
                                    <th>Nombre Titulada</th>
                                    <th>Votantes</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                for ($i = 0; $i < count($this->votantes); $i++) {
                                    ?>
                                    <tr>
                                        <td><?php echo $this->votantes[$i]['tnesFicha'] ?></td>
                                        <td><?php echo $this->votantes[$i]['pmasNombre'] ?></td>
                                        <td><?php echo $this->votantes[$i]['cantidad'] ?></td>
                                    </tr>
                                    <?php
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>