<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="panel panel-default sombra">
                <div class="panel-heading"><h4 class="label-orange">Numero de votos por candidato</h4></div>
                <div class="panel-body">

                    <?php
                    $width = "width='90%'";
                    $maximo = $this->votostotal[0][0];
                    echo "<table align='center' " . $width . " >";
                    for ($i = 0; $i < count($this->votos); $i++) {
                        mt_srand((double) microtime() * 1000000);
                        $color = '';
                        while (strlen($color) < 6) {
                            $color .= sprintf("%02X", mt_rand(0, 255));
                        }
                        $porcentaje = round((($this->votos[$i]['Cantidad'] / $maximo) * 100), 2);
                        echo "<tr bgcolor=''>
				<td width='40%'><strong>" . $this->votos[$i]['Nombre'] . "</strong></td>    
				<td width='10%'><div align='center'>" . $this->votos[$i]['Cantidad'] . "</div></td>
				<td width='10%'><div align='center'>" . $porcentaje . "%</div></td>
				<td width='40%'>        
					<table width='" . $porcentaje . "%' cellspacing='1' cellpadding='1' border='1'>        
						<tr bgcolor='" . $color . "'><td>&nbsp;</td></tr>    
					</table>
				</td>    
			</tr>";
                    }
                    echo "</table>";
                    ?>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>